# Date: August 23, 2025
# Author: Julian di Giovanni w/Claude.ai - Version 1.0 Defensemen Performance Edition
# Version: 1.0 - Dual Defensemen Performance Prediction (Points + Plus/Minus)

"""
DEFENSEMEN PERFORMANCE PREDICTION PROGRAM: NHL Defensemen Points and Plus/Minus Modeling
=======================================================================================

This program builds machine learning models to predict NHL defensemen performance using 
historical (lagged) performance data including individual stats, team context, player experience, 
and non-linear interactions. Version 1.0 creates dual prediction models for defensemen:
1. Points per game prediction
2. Plus/minus prediction

The predictions are then combined to rank defensemen based on total performance (points + plus/minus).

PROGRAM OVERVIEW:
================
This defensemen-focused program adapts the forward points prediction methodology to model
defensemen performance across two key metrics that define defensive contribution:
- Offensive contribution (points per game)
- Two-way play effectiveness (plus/minus)

The dual-model approach recognizes that defensemen contribute differently than forwards,
with plus/minus being a critical metric for evaluating defensive play and overall
ice presence impact.

MAJOR FEATURES IN VERSION 1.0:
==============================
1. **DUAL TARGET MODELING**: Separate models for points per game and plus/minus
2. **DEFENSEMEN FOCUS**: Filters for position = D only (removes forwards)
3. **COMBINED RANKINGS**: Ranks players by points + plus/minus for total impact
4. **EXPERIENCE FEATURES**: Years played with interaction terms for career curves
5. **COVID CONTROLS**: Special handling for 2019-2020 and 2020-2021 seasons
6. **NON-LINEAR FEATURES**: Polynomial terms and interaction effects
7. **TEAM CONTEXT**: Updated single team structure (wins to face_off_win_pct_team)
8. **DUAL PROJECTIONS**: Both actual games and 82-game projections for each metric

EXPECTED FOLDER STRUCTURE:
=========================
project_folder/
├── defense_performance_model_v1.py (this script)
├── data_output/                    (input data folder)
│   ├── skater_team_data.csv       (merged player-team data - PRIMARY INPUT)
│   └── goalie_team_data.csv       (merged goalie-team data - optional)
├── nhl_plots/                     (output plots - created automatically)
└── nhl_results/                   (output results - created automatically)

REQUIRED INPUT FILE:
===================
- Primary: data_output/skater_team_data.csv (merged NHL player and team statistics)
- This file should contain player statistics merged with team information
- Team statistics run from "wins" to "face_off_win_pct_team" columns
- Must include plus/minus data for defensemen modeling
- Generated by the NHL data merger script from the NHL API data

DATA STRUCTURE EXPECTATIONS:
===========================
- Team ID column: "team_id"
- Team statistics: "wins" through "face_off_win_pct_team"
- Player points: "points_player" or calculated from "goals" + "assists"
- Plus/minus: "plus_minus", "plusMinus", or similar variations
- Games played: "games_played"
- Position: "position" column with "D" for defensemen

DEFENSEMEN-SPECIFIC CONSIDERATIONS:
==================================
1. **Plus/Minus Importance**: Critical metric for defensemen evaluation
2. **Different Scoring Patterns**: Lower point totals but more focus on defensive metrics
3. **Ice Time Relevance**: Defensemen typically play more minutes per game
4. **Power Play Role**: Different PP responsibilities (quarterbacking vs. net presence)
5. **Career Longevity**: Defensemen often have longer careers than forwards

WORKFLOW STEP-BY-STEP:
======================

1. DATA LOADING & CLEANING:
   - Loads NHL skater data from data_output/skater_team_data.csv
   - **DEFENSE FOCUS**: Keeps only defensemen (position = D), removes forwards
   - Calculates points per game and validates plus/minus data
   - Identifies COVID seasons (2019-2020, 2020-2021) for special handling
   - Calculates years played for each player based on first/current season
   - Parses seasons and extracts year information
   - Handles missing data in core statistics including plus/minus

2. EXPERIENCE AND TEMPORAL FEATURE CREATION:
   - Calculates years played for each player (career length measure)
   - Creates COVID season indicator variables
   - Develops polynomial terms (years_played^2, years_played^3)
   - Engineers interaction terms between years played and key defensive stats

3. LAG FEATURE CREATION WITH DEFENSIVE FOCUS:
   - Creates 1, 2, or 3-year historical lags for key statistics
   - Individual defensive stats: goals, assists, shots, games_played, plus_minus
   - Advanced metrics: shooting_pct, time_on_ice_per_game (crucial for defensemen)
   - Power play stats: pp_goals, pp_assists, pp_shots, etc.
   - Team statistics from restructured single-team format
   - Filters data to years where complete lag history is available

4. DUAL FEATURE ENGINEERING:
   - Creates advanced metrics from lagged data for both targets
   - Points-focused features: offensive zone deployment, scoring trends
   - Plus/minus-focused features: defensive reliability, consistency metrics
   - Experience-based feature engineering with defensive career curves
   - Non-linear transformations and polynomial features
   - Interaction effects between experience and defensive performance
   - Team context metrics from lagged team statistics

5. DUAL MODEL TRAINING:
   - **Model 1**: Points per game prediction using offensive-focused features
   - **Model 2**: Plus/minus prediction using defensive-focused features
   - Both models use the same lag structure and regularization approach
   - Enhanced regularization for increased feature complexity
   - Cross-validation with time-aware splits for both models

6. COMBINED PREDICTION AND RANKING:
   - Predicts points per game for 2024-2025 defensemen
   - Predicts plus/minus for 2024-2025 defensemen
   - **DUAL PROJECTIONS**: Converts to total points and plus/minus using both:
     (a) actual games played and (b) 82 games
   - **COMBINED RANKING**: Ranks defensemen by (predicted points + predicted plus/minus)
   - Provides comprehensive defensemen performance evaluation

KEY FEATURES FOR DEFENSEMEN MODELING:
====================================
- **DUAL TARGET APPROACH**: Separate models for offensive and defensive contributions
- **PLUS/MINUS VALIDATION**: Ensures plus/minus data quality and availability
- **DEFENSIVE METRICS FOCUS**: Emphasizes metrics relevant to defensive play
- **CAREER CURVE MODELING**: Accounts for different aging patterns in defensemen
- **ICE TIME CONSIDERATIONS**: Factors in higher average ice time for defensemen
- **TEAM IMPACT MODELING**: Enhanced team context for plus/minus prediction
- **POWER PLAY DIFFERENTIATION**: Different PP role modeling for defensemen
- **CONSISTENCY EMPHASIS**: Values defensive reliability over offensive volatility
- **EXPERIENCE INTERACTIONS**: Models how defensive skills evolve with experience
- **COMBINED PERFORMANCE METRIC**: Total impact = offensive + defensive contributions

TECHNICAL APPROACH:
==================
- Maintains all regularization techniques from forward model
- Enhanced feature engineering for defensive-specific metrics
- Updated team feature identification for new data structure
- COVID season handling with defensive performance considerations
- Polynomial regularization for non-linear defensive career curves
- Dual model architecture with separate optimization for each target
- Combined prediction framework for total defensemen evaluation

OUTPUT:
======
1. **Points per game model performance** for defensemen
2. **Plus/minus model performance** for defensemen
3. **Combined rankings** by (points + plus/minus) total impact
4. **Dual projections** for both metrics (actual games vs 82 games)
5. **Experience feature importance** analysis for defensive careers
6. **COVID season impact** assessment on defensive performance
7. **Defensive career curve analysis** with aging patterns
8. **Top 50 defensemen rankings** by combined performance metric

This version provides comprehensive defensemen evaluation by modeling both offensive
contribution (points) and defensive effectiveness (plus/minus), creating a complete
picture of defensemen performance for hockey analytics.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV, TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.feature_selection import SelectKBest, f_regression, RFECV
from sklearn.preprocessing import StandardScaler, RobustScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Tuple, Dict, Any, List
import warnings
import os
import sys
from datetime import datetime
warnings.filterwarnings('ignore')

class OutputManager:
    """Manages output to both console and file"""
    def __init__(self, output_file=None):
        self.terminal = sys.stdout
        self.log_file = None
        if output_file:
            os.makedirs(os.path.dirname(output_file), exist_ok=True)
            self.log_file = open(output_file, 'w')
    
    def write(self, message):
        self.terminal.write(message)
        if self.log_file:
            self.log_file.write(message)
    
    def flush(self):
        self.terminal.flush()
        if self.log_file:
            self.log_file.flush()
    
    def close(self):
        if self.log_file:
            self.log_file.close()

def find_csv_file() -> str:
    """
    Find the CSV data file in the data_output folder or other common locations.
    
    Expected primary location: data_output/skater_team_data.csv
    This file should be the merged player-team data from the NHL data merger script
    with the new single-team structure including defensemen data.
    
    Returns:
        Path to the CSV file if found
        
    Raises:
        FileNotFoundError: If CSV file cannot be found in any location
    """
    current_dir = os.getcwd()
    print(f"Current working directory: {current_dir}")
    
    # Primary file names to search for (in priority order)
    possible_filenames = [
        'skater_team_data.csv',     # Primary: merged player-team data
        'nhl_skater_data.csv', 
        'skater_data.csv',
        'hockey_data.csv',
        'nhl_data.csv'
    ]
    
    # Directory patterns to search in (in priority order)
    search_patterns = [
        'data_output',              # PRIMARY: expected location for merged data
        '',                         # Current directory
        'nhl_output',              # Legacy location
        'data',                    # Alternative data folder
        'hockeyanalytics/nhl_output',  # Legacy nested structure
        'Dropbox/hockeyanalytics/nhl_output',
        'Documents',
        'Desktop',
        'Downloads'
    ]
    
    print("\nSearching for CSV file (prioritizing data_output folder)...")
    
    for filename in possible_filenames:
        for pattern in search_patterns:
            if pattern:
                search_path = os.path.join(current_dir, pattern, filename)
            else:
                search_path = os.path.join(current_dir, filename)
            
            print(f"  Checking: {search_path}")
            if os.path.exists(search_path):
                print(f"Found CSV file: {search_path}")
                return search_path
    
    # If not found, provide helpful error message
    print("\nCSV file not found in expected locations.")
    print("\nExpected folder structure for defensemen model v1.0:")
    print(f"  {current_dir}/")
    print(f"  ├── defense_performance_model_v1.py (this script)")
    print(f"  ├── data_output/")
    print(f"  │   ├── skater_team_data.csv (PRIMARY INPUT - merged player-team data)")
    print(f"  │   └── goalie_team_data.csv (optional)")
    print(f"  ├── nhl_plots/ (created automatically)")
    print(f"  └── nhl_results/ (created automatically)")
    
    print(f"\nPlease ensure your merged player-team data file is located at:")
    print(f"  {os.path.join(current_dir, 'data_output', 'skater_team_data.csv')}")
    
    # Ask user for file path
    user_path = input("\nEnter the full path to your CSV file (or press Enter to exit): ").strip()
    if user_path and os.path.exists(user_path):
        return user_path
    elif user_path:
        raise FileNotFoundError(f"File not found: {user_path}")
    else:
        raise FileNotFoundError("No CSV file specified")

def setup_output_directories() -> Tuple[str, str]:
    """
    Create output directories relative to current working directory.
    
    Returns:
        Tuple of (plots_dir, results_dir) paths
    """
    current_dir = os.getcwd()
    
    # Create output directories relative to current directory
    plots_dir = os.path.join(current_dir, 'nhl_plots')
    results_dir = os.path.join(current_dir, 'nhl_results')
    
    os.makedirs(plots_dir, exist_ok=True)
    os.makedirs(results_dir, exist_ok=True)
    
    print(f"Output directories created:")
    print(f"  Plots: {plots_dir}")
    print(f"  Results: {results_dir}")
    
    return plots_dir, results_dir

class DefensemenDualPerformancePredictor:
    """
    NHL Defensemen Dual Performance Predictor v1.0
    
    Predicts both points per game and plus/minus for defensemen, then combines
    the predictions to rank defensemen by total impact (points + plus/minus).
    
    Key features:
    - Dual target modeling for comprehensive defensemen evaluation
    - Defensive-specific feature engineering
    - Combined performance ranking system
    """
    
    def __init__(self, lag_years: int = 2, min_training_year: int = None, use_feature_selection: bool = True):
        """
        Initialize the dual defensemen predictor.
        
        Args:
            lag_years: Number of years of historical data to use (1, 2, or 3)
            min_training_year: Minimum year to include in training (auto-calculated if None)
            use_feature_selection: Whether to apply automatic feature selection
        """
        # Scalers for both models
        self.scaler_points = RobustScaler()
        self.scaler_plusminus = RobustScaler()
        
        # Models for dual prediction
        self.model_points = None
        self.model_plusminus = None
        
        # Feature selectors
        self.feature_selector_points = None
        self.feature_selector_plusminus = None
        
        # Feature columns
        self.feature_columns = None
        self.selected_features_points = None
        self.selected_features_plusminus = None
        
        # Target columns
        self.target_points = 'points_per_game'
        self.target_plusminus = 'plus_minus_per_game'
        
        self.lag_years = lag_years
        self.min_training_year = min_training_year
        self.use_feature_selection = use_feature_selection
        self.best_params_points = None
        self.best_params_plusminus = None
        
    def load_data(self, csv_path: str) -> pd.DataFrame:
        """
        Load hockey defensemen statistics and create enhanced features.
        
        DEFENSE FOCUS: Keeps only defensemen (position = D) and validates plus/minus data.
        
        Args:
            csv_path: Path to the merged player-team CSV file
            
        Returns:
            Enhanced DataFrame with defensemen data and dual targets
        """
        df = pd.read_csv(csv_path)
        
        print(f"Original data shape: {df.shape}")
        print(f"Loaded merged player-team data from: {csv_path}")
        
        # DEFENSE FOCUS: Keep only defensemen - check multiple position column names
        position_cols = ['position', 'pos', 'Position', 'Pos']
        position_col = None
        
        for col in position_cols:
            if col in df.columns:
                position_col = col
                break
        
        if position_col:
            original_count = len(df)
            # Keep only defensemen (position = D)
            df = df[df[position_col].astype(str).str.upper().str.contains('D', na=False)]
            kept_count = len(df)
            removed_count = original_count - kept_count
            print(f"Filtered for defensemen only: kept {kept_count}, removed {removed_count} forwards/other positions")
            print(f"Remaining positions: {df[position_col].value_counts().to_dict()}")
        else:
            print("Warning: No position column found - cannot filter for defensemen")
            print(f"Available columns: {list(df.columns)}")
        
        # Parse season to extract start year
        df['season_str'] = df['season'].astype(str)
        df['year'] = df['season_str'].str[:4].astype(int)
        
        print(f"Year range: {df['year'].min()} - {df['year'].max()}")
        print(f"Years in dataset: {sorted(df['year'].unique())}")
        
        # Create dual target variables
        df = self._create_dual_targets(df)
        
        # Create COVID season indicators
        df = self._create_covid_season_indicators(df)
        
        # Calculate years played for each player
        df = self._calculate_years_played(df)
        
        # Automatically set min_training_year if not specified
        if self.min_training_year is None:
            self.min_training_year = df['year'].min() + self.lag_years
            print(f"Auto-setting min_training_year to {self.min_training_year} (allows {self.lag_years}-year lags)")
        
        # Clean missing data issues
        df = self._clean_missing_data(df)
        
        # Sort by player and year for lag feature creation
        df = df.sort_values(['player_id', 'year'])
        
        # Show data availability by year
        year_counts = df['year'].value_counts().sort_index()
        print(f"\nObservations per year (defensemen only):")
        for year, count in year_counts.items():
            covid_indicator = " (COVID)" if year in [2019, 2020] else ""
            print(f"  {year}: {count} defenseman-seasons{covid_indicator}")
        
        return df
    
    def _create_dual_targets(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Create dual target variables: points per game and plus/minus per game.
        
        Args:
            df: DataFrame with player statistics
            
        Returns:
            DataFrame with dual target variables for defensemen
        """
        print("\nCreating dual target variables for defensemen...")
        
        # Create points per game target
        if 'points_player' in df.columns:
            df['total_points'] = df['points_player'].fillna(0)
            print("Using 'points_player' column for points calculation")
        elif 'goals' in df.columns and 'assists' in df.columns:
            df['total_points'] = df['goals'].fillna(0) + df['assists'].fillna(0)
            print("Calculating points from goals + assists")
        else:
            raise ValueError("Cannot find points_player column or goals+assists columns")
        
        # Handle games played column variations
        games_played_cols = ['games_played_player', 'games_played', 'gamesPlayed', 'GP', 'Games', 'games']
        games_played_col = None
        
        for col in games_played_cols:
            if col in df.columns:
                games_played_col = col
                break
        
        if games_played_col:
            df['games_played'] = df[games_played_col].fillna(0).clip(lower=0)
        else:
            raise ValueError(f"Cannot find games played column. Available columns: {list(df.columns)}")
        
        # Create points per game
        valid_games_mask = df['games_played'] > 0
        df.loc[valid_games_mask, 'points_per_game'] = (
            df.loc[valid_games_mask, 'total_points'] / df.loc[valid_games_mask, 'games_played']
        )
        df.loc[~valid_games_mask, 'points_per_game'] = 0
        
        # Create plus/minus per game target
        plusminus_cols = ['plus_minus', 'plusMinus', 'plus_minus_player', 'pm', 'PM']
        plusminus_col = None
        
        for col in plusminus_cols:
            if col in df.columns:
                plusminus_col = col
                break
        
        if plusminus_col:
            df['total_plus_minus'] = df[plusminus_col].fillna(0)
            print(f"Using '{plusminus_col}' column for plus/minus calculation")
        else:
            print("Warning: No plus/minus column found - creating placeholder")
            df['total_plus_minus'] = 0
        
        # Create plus/minus per game
        df.loc[valid_games_mask, 'plus_minus_per_game'] = (
            df.loc[valid_games_mask, 'total_plus_minus'] / df.loc[valid_games_mask, 'games_played']
        )
        df.loc[~valid_games_mask, 'plus_minus_per_game'] = 0
        
        # Statistics for both targets
        ppg_stats = df[df['points_per_game'] > 0]['points_per_game'].describe()
        pm_stats = df['plus_minus_per_game'].describe()
        
        print(f"Points per game statistics (defensemen):")
        print(f"  Mean: {ppg_stats['mean']:.3f}")
        print(f"  Median: {ppg_stats['50%']:.3f}")
        print(f"  Max: {ppg_stats['max']:.3f}")
        
        print(f"Plus/minus per game statistics (defensemen):")
        print(f"  Mean: {pm_stats['mean']:.3f}")
        print(f"  Median: {pm_stats['50%']:.3f}")
        print(f"  Range: {pm_stats['min']:.3f} to {pm_stats['max']:.3f}")
        
        return df
    
    def _create_covid_season_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """Create indicator variables for COVID-affected seasons."""
        print("\nCreating COVID season indicators...")
        
        df['covid_2019_2020'] = (df['year'] == 2019).astype(int)
        df['covid_2020_2021'] = (df['year'] == 2020).astype(int)
        df['covid_season'] = ((df['year'] == 2019) | (df['year'] == 2020)).astype(int)
        
        covid_2019_count = df['covid_2019_2020'].sum()
        covid_2020_count = df['covid_2020_2021'].sum()
        total_covid = df['covid_season'].sum()
        
        print(f"COVID season indicators created:")
        print(f"  2019-2020 season observations: {covid_2019_count}")
        print(f"  2020-2021 season observations: {covid_2020_count}")
        print(f"  Total COVID-affected observations: {total_covid}")
        
        return df
    
    def _calculate_years_played(self, df: pd.DataFrame) -> pd.DataFrame:
        """Calculate years played (career experience) for each defenseman."""
        print("\nCalculating years played (experience features)...")
        
        # Calculate first season for each player
        first_seasons = df.groupby('player_id')['year'].min().reset_index()
        first_seasons.rename(columns={'year': 'first_season_year'}, inplace=True)
        
        # Merge back to main dataframe
        df = df.merge(first_seasons, on='player_id', how='left')
        
        # Calculate years played
        df['years_played'] = df['year'] - df['first_season_year'] + 1
        df['years_played'] = df['years_played'].clip(lower=1, upper=25)
        
        # Create polynomial terms for non-linear career effects
        df['years_played_squared'] = df['years_played'] ** 2
        df['years_played_cubed'] = df['years_played'] ** 3
        
        # Career stage indicators
        df['rookie_year'] = (df['years_played'] == 1).astype(int)
        df['prime_years'] = ((df['years_played'] >= 3) & (df['years_played'] <= 12)).astype(int)
        df['veteran_years'] = (df['years_played'] > 12).astype(int)
        
        # Experience statistics
        exp_stats = df['years_played'].describe()
        print(f"Years played statistics (defensemen):")
        print(f"  Mean: {exp_stats['mean']:.1f} years")
        print(f"  Median: {exp_stats['50%']:.1f} years")
        print(f"  Max: {exp_stats['max']:.0f} years")
        print(f"  Rookies (1 year): {df['rookie_year'].sum()} observations")
        print(f"  Prime years (3-12): {df['prime_years'].sum()} observations")
        print(f"  Veterans (>12 years): {df['veteran_years'].sum()} observations")
        
        return df
    
    def _clean_missing_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """Clean and handle missing data for defensemen."""
        print("\nCleaning missing data...")
        
        # Handle shooting percentage
        shooting_cols = ['shooting_pct', 'shooting_percentage', 'sh_pct', 'shootingPct']
        shooting_col = None
        for col in shooting_cols:
            if col in df.columns:
                shooting_col = col
                break
        
        if shooting_col:
            if df[shooting_col].max() > 1:
                df['shooting_pct'] = df[shooting_col] / 100
            else:
                df['shooting_pct'] = df[shooting_col]
        else:
            # Calculate from goals and shots if available
            goals_cols = ['goals', 'Goals', 'G']
            shots_cols = ['shots', 'Shots', 'S']
            
            goals_col = shots_col = None
            for col in goals_cols:
                if col in df.columns:
                    goals_col = col
                    break
            for col in shots_cols:
                if col in df.columns:
                    shots_col = col
                    break
            
            if goals_col and shots_col:
                df['shooting_pct'] = df[goals_col] / df[shots_col].replace(0, np.nan)
                df['shooting_pct'] = df['shooting_pct'].fillna(0.05)  # Lower default for defensemen
                if goals_col != 'goals':
                    df['goals'] = df[goals_col]
                if shots_col != 'shots':
                    df['shots'] = df[shots_col]
            else:
                df['shooting_pct'] = 0.05  # Lower default for defensemen
        
        # Handle time on ice
        toi_cols = ['time_on_ice_per_game', 'toi_per_game', 'avg_toi', 'timeOnIcePerGame', 'TOI']
        toi_col = None
        for col in toi_cols:
            if col in df.columns:
                toi_col = col
                break
        
        if toi_col and toi_col != 'time_on_ice_per_game':
            df['time_on_ice_per_game'] = df[toi_col]
        elif not toi_col:
            df['time_on_ice_per_game'] = 20.0  # Higher default for defensemen
        
        # Handle assists
        assists_cols = ['assists', 'Assists', 'A']
        assists_col = None
        for col in assists_cols:
            if col in df.columns:
                assists_col = col
                break
        if assists_col and assists_col != 'assists':
            df['assists'] = df[assists_col]
        
        # Clean up core statistical columns
        core_stats = ['goals', 'assists', 'shots', 'games_played', 'total_points', 'total_plus_minus']
        for stat in core_stats:
            if stat in df.columns:
                df[stat] = df[stat].fillna(0)
                df[stat] = df[stat].clip(lower=0 if stat != 'total_plus_minus' else -100)
        
        # Remove rows with essential missing data
        essential_cols = ['player_id', 'year', 'games_played']
        before_essential = len(df)
        df = df.dropna(subset=essential_cols)
        after_essential = len(df)
        
        if before_essential != after_essential:
            print(f"Removed {before_essential - after_essential} rows missing essential data")
        
        # Remove players with 0 games played
        before_games = len(df)
        df = df[df['games_played'] > 0]
        after_games = len(df)
        if before_games != after_games:
            print(f"Removed {before_games - after_games} rows with 0 games played")
        
        print(f"Data shape after cleaning: {df.shape}")
        return df
    
    def create_lag_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Create lagged features for defensemen with both offensive and defensive focus."""
        # Individual stats for lagging (defensive focus)
        individual_features = ['goals', 'assists', 'shots', 'games_played', 'shooting_pct', 
                             'time_on_ice_per_game', 'points_per_game', 'total_points',
                             'plus_minus_per_game', 'total_plus_minus']
        
        # Power play features
        pp_features = [col for col in df.columns if col.startswith('pp') and 'lag' not in col]
        
        # Team features
        team_features = self._identify_team_features(df)
        
        # Experience features to lag
        experience_features = ['years_played', 'years_played_squared', 'years_played_cubed']
        
        # Combine all features for lagging
        all_lag_features = individual_features + pp_features + team_features + experience_features
        existing_features = [f for f in all_lag_features if f in df.columns]
        
        print(f"\nCreating {self.lag_years}-year lags for {len(existing_features)} defensemen features:")
        print(f"  Individual stats: {len([f for f in existing_features if f in individual_features])}")
        print(f"  Power play stats: {len([f for f in existing_features if f in pp_features])}")
        print(f"  Team statistics: {len([f for f in existing_features if f in team_features])}")
        print(f"  Experience features: {len([f for f in existing_features if f in experience_features])}")
        
        df_with_lags = df.copy()
        
        # Create lag columns
        lag_columns = []
        for feature in existing_features:
            for lag in range(1, self.lag_years + 1):
                lag_col = f'{feature}_lag{lag}'
                lag_columns.append(lag_col)
                df_with_lags[lag_col] = np.nan
        
        print(f"  Total lag columns created: {len(lag_columns)}")
        
        # Create lags for each player individually
        players_with_sufficient_history = 0
        
        for player in df['player_id'].unique():
            player_data = df[df['player_id'] == player].sort_values('year')
            
            if len(player_data) > self.lag_years:
                players_with_sufficient_history += 1
                
                for feature in existing_features:
                    for lag in range(1, self.lag_years + 1):
                        lag_col = f'{feature}_lag{lag}'
                        lagged_values = player_data[feature].shift(lag)
                        df_with_lags.loc[df_with_lags['player_id'] == player, lag_col] = lagged_values
        
        print(f"Defensemen with sufficient history: {players_with_sufficient_history}")
        
        # Filter to training years
        training_data = df_with_lags[df_with_lags['year'] >= self.min_training_year].copy()
        print(f"Training data shape after year filter: {training_data.shape}")
        
        return training_data
    
    def _identify_team_features(self, df: pd.DataFrame) -> List[str]:
        """Identify team features for defensemen analysis."""
        team_features = []
        
        # Check for expected team structure
        if 'wins' in df.columns and 'face_off_win_pct_team' in df.columns:
            cols = list(df.columns)
            try:
                start_idx = cols.index('wins')
                end_idx = cols.index('face_off_win_pct_team')
                team_features = cols[start_idx:end_idx+1]
                print(f"  Identified {len(team_features)} team features for defensemen analysis")
            except ValueError:
                print("  Warning: Could not find team feature range")
        
        # Fallback: look for team-like features
        if not team_features:
            possible_team_cols = [col for col in df.columns if any(indicator in col.lower() 
                                 for indicator in ['team', 'wins', 'losses', 'goals_for', 'goals_against'])]
            team_features.extend(possible_team_cols)
        
        # Keep only numeric features
        numeric_team_features = []
        for col in team_features:
            if col in df.columns:
                try:
                    pd.to_numeric(df[col], errors='raise')
                    numeric_team_features.append(col)
                except:
                    continue
        
        return numeric_team_features
    
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """Enhanced feature engineering for defensemen with dual target focus."""
        print(f"\nEngineering defensemen features with dual target focus...")
        
        df_eng = df.copy()
        
        # Find all lag columns
        lag_columns = [col for col in df_eng.columns if 'lag' in col]
        
        if lag_columns:
            print(f"Found {len(lag_columns)} lag columns for defensemen feature engineering")
            
            # Get base features that have lags
            base_features = list(set([col.replace('_lag1', '').replace('_lag2', '').replace('_lag3', '') 
                                    for col in lag_columns]))
            
            print(f"Engineering features for {len(base_features)} base defensemen features")
            
            # Standard lag-based features
            for base_feature in base_features:
                lag_cols = [col for col in lag_columns if col.startswith(f'{base_feature}_lag')]
                
                if lag_cols:
                    # Historical averages
                    df_eng[f'{base_feature}_hist_avg'] = df_eng[lag_cols].mean(axis=1, skipna=True)
                    
                    # Historical consistency (if multiple lags)
                    if len(lag_cols) >= 2:
                        df_eng[f'{base_feature}_hist_std'] = df_eng[lag_cols].std(axis=1, skipna=True).fillna(0)
                    
                    # Recent trends
                    if len(lag_cols) >= 2:
                        if f'{base_feature}_lag1' in df_eng.columns and f'{base_feature}_lag2' in df_eng.columns:
                            trend = df_eng[f'{base_feature}_lag1'] - df_eng[f'{base_feature}_lag2']
                            df_eng[f'{base_feature}_trend'] = trend.fillna(0)
            
            # Defensemen-specific feature engineering
            self._create_defensive_interactions(df_eng, lag_columns)
            self._create_covid_interactions(df_eng, lag_columns)
            self._create_career_trajectory_features(df_eng)
        
        # Create defensive-specific per-game rates
        for lag in range(1, min(self.lag_years + 1, 3)):
            if f'goals_lag{lag}' in df_eng.columns and f'games_played_lag{lag}' in df_eng.columns:
                goals_per_game = df_eng[f'goals_lag{lag}'] / df_eng[f'games_played_lag{lag}'].replace(0, np.nan)
                df_eng[f'goals_per_game_lag{lag}'] = goals_per_game.fillna(0)
                
            if f'assists_lag{lag}' in df_eng.columns and f'games_played_lag{lag}' in df_eng.columns:
                assists_per_game = df_eng[f'assists_lag{lag}'] / df_eng[f'games_played_lag{lag}'].replace(0, np.nan)
                df_eng[f'assists_per_game_lag{lag}'] = assists_per_game.fillna(0)
            
            # Plus/minus rate (important for defensemen)
            if f'total_plus_minus_lag{lag}' in df_eng.columns and f'games_played_lag{lag}' in df_eng.columns:
                pm_per_game = df_eng[f'total_plus_minus_lag{lag}'] / df_eng[f'games_played_lag{lag}'].replace(0, np.nan)
                df_eng[f'pm_per_game_lag{lag}'] = pm_per_game.fillna(0)
        
        # Clean up infinite and extreme values
        df_eng = df_eng.replace([np.inf, -np.inf], np.nan)
        
        # Fill remaining NaN values
        numeric_cols = df_eng.select_dtypes(include=[np.number]).columns
        df_eng[numeric_cols] = df_eng[numeric_cols].fillna(0)
        
        print(f"Final engineered defensemen data shape: {df_eng.shape}")
        
        return df_eng
    
    def _create_defensive_interactions(self, df_eng: pd.DataFrame, lag_columns: List[str]) -> None:
        """Create interaction terms specific to defensemen performance."""
        print("  Creating defensemen interaction terms...")
        
        # Key defensive performance metrics for interactions
        key_defensive_lags = [col for col in lag_columns 
                             if any(metric in col for metric in ['plus_minus_lag', 'time_on_ice_lag', 'goals_lag', 'assists_lag'])]
        
        # Create interactions with years_played
        interaction_count = 0
        for perf_col in key_defensive_lags[:12]:  # Focus on key metrics
            if perf_col in df_eng.columns and 'years_played' in df_eng.columns:
                interaction_name = f'{perf_col}_x_experience'
                df_eng[interaction_name] = df_eng[perf_col] * df_eng['years_played']
                interaction_count += 1
        
        print(f"    Created {interaction_count} defensive interaction terms")
    
    def _create_covid_interactions(self, df_eng: pd.DataFrame, lag_columns: List[str]) -> None:
        """Create COVID season interaction effects for defensemen."""
        print("  Creating COVID season interaction terms for defensemen...")
        
        # Metrics that might be affected differently during COVID for defensemen
        covid_metrics = [col for col in lag_columns 
                        if any(metric in col for metric in ['plus_minus_lag', 'time_on_ice_lag', 'points_per_game_lag'])]
        
        covid_interaction_count = 0
        for metric in covid_metrics[:8]:
            if metric in df_eng.columns and 'covid_season' in df_eng.columns:
                interaction_name = f'{metric}_x_covid'
                df_eng[interaction_name] = df_eng[metric] * df_eng['covid_season']
                covid_interaction_count += 1
        
        print(f"    Created {covid_interaction_count} COVID interaction terms")
    
    def _create_career_trajectory_features(self, df_eng: pd.DataFrame) -> None:
        """Create career trajectory features for defensemen."""
        print("  Creating defensemen career trajectory features...")
        
        trajectory_features = 0
        
        # Defensive career stage performance
        if 'plus_minus_per_game_lag1' in df_eng.columns:
            if 'rookie_year' in df_eng.columns:
                df_eng['rookie_defensive_performance'] = df_eng['plus_minus_per_game_lag1'] * df_eng['rookie_year']
                trajectory_features += 1
            
            if 'prime_years' in df_eng.columns:
                df_eng['prime_defensive_performance'] = df_eng['plus_minus_per_game_lag1'] * df_eng['prime_years']
                trajectory_features += 1
        
        print(f"    Created {trajectory_features} career trajectory features")
    
    def prepare_features(self, df: pd.DataFrame, target_type: str = 'both') -> Tuple[pd.DataFrame, pd.Series, pd.Series]:
        """
        Prepare feature matrix and targets for dual model training.
        
        Args:
            df: DataFrame with all engineered features
            target_type: 'points', 'plusminus', or 'both'
            
        Returns:
            Tuple of (feature matrix X, points target y1, plus/minus target y2)
        """
        print(f"\nPreparing features for defensemen dual prediction")
        print(f"Target type: {target_type}")
        print(f"Initial data shape: {len(df)} observations and {len(df.columns)} columns")
        
        # CRITICAL: Exclude ALL contemporaneous variables to prevent data leakage
        exclude_cols = [
            # Core identifiers
            'player_id', 'season', 'season_str', 'year', 'first_season_year',
            # Team identifiers and names
            'team_id', 'team_code', 'team_name', 'teamId', 'teamCode', 'teamName', 'team',
            # Target variables (current season)
            'points_per_game', 'plus_minus_per_game', 'total_points', 'total_plus_minus',
            # Basic current season stats
            'goals', 'assists', 'shots', 'games_played_player', 'games_played',
            'shooting_pct', 'time_on_ice_per_game', 'plus_minus', 'plusMinus',
            # Additional current season stats that could leak
            'gw_goals', 'ot_goals', 'penalty_minutes', 'pim', 'hits', 'blocked_shots',
            'takeaways', 'giveaways', 'faceoff_wins', 'faceoffs_taken', 'shifts',
            # Current season experience (use lagged instead)
            'years_played', 'years_played_squared', 'years_played_cubed', 
            'rookie_year', 'prime_years', 'veteran_years',
            # Position and demographic info
            'position', 'pos', 'Position', 'Pos', 'age', 'height', 'weight',
        ]
        
        # COMPREHENSIVE: Exclude ALL current season variables (anything without 'lag' in the name)
        print("  Identifying and excluding ALL current season variables...")
        current_season_excluded = 0
        
        for col in df.columns:
            # Skip if already in exclude list or is a lag variable
            if col in exclude_cols or 'lag' in col:
                continue
                
            # Exclude ALL remaining non-lag variables that could be current season stats
            if any(indicator in col.lower() for indicator in [
                'pp_', 'sh_', 'pk_', 'sv_', 'goals', 'assists', 'shots', 'points', 
                'plus_minus', 'pm_', 'penalty', 'pim', 'hits', 'blocks', 'takeaway',
                'giveaway', 'faceoff', 'shift', 'ice_time', 'toi', 'saves', 'wins',
                'losses', 'ties', 'otl', 'points_pct', 'gf_', 'ga_', 'diff',
                'streak', 'home_', 'away_', 'last_10', 'percent', 'rate', 'avg'
            ]):
                # Double-check it's not a lag variable or engineered feature we want to keep
                if ('lag' not in col and 'hist' not in col and 'trend' not in col and 
                    'covid' not in col and '_x_' not in col):
                    exclude_cols.append(col)
                    current_season_excluded += 1
        
        print(f"  Excluded {current_season_excluded} additional current season variables")
        
        # Exclude text/name columns
        name_indicators = ['name', 'player', 'firstname', 'lastname', 'full_name', 'player_name']
        for col in df.columns:
            if any(indicator in col.lower() for indicator in name_indicators):
                exclude_cols.append(col)
        
        exclude_cols = list(set(exclude_cols))
        potential_features = [col for col in df.columns if col not in exclude_cols]
        
        print(f"Potential features after exclusions: {len(potential_features)}")
        
        # Keep only numeric features
        numeric_features = []
        for col in potential_features:
            if col in df.columns:
                try:
                    pd.to_numeric(df[col], errors='raise')
                    numeric_features.append(col)
                except (ValueError, TypeError):
                    try:
                        pd.to_numeric(df[col], errors='coerce')
                        numeric_features.append(col)
                        print(f"  Converting '{col}' to numeric")
                    except:
                        print(f"  Excluding non-numeric column: '{col}'")
        
        # Remove features with excessive missing data
        good_features = []
        for col in numeric_features:
            missing_pct = df[col].isnull().sum() / len(df) * 100
            if missing_pct <= 70:
                good_features.append(col)
            else:
                print(f"Excluding '{col}' due to {missing_pct:.1f}% missing data")
        
        self.feature_columns = good_features
        print(f"Final feature count: {len(self.feature_columns)}")
        
        # Feature categorization for defensemen
        individual_features = [f for f in self.feature_columns if 'lag' in f and 
                             not f.startswith('pp') and not any(team_f in f for team_f in ['wins', 'losses'])]
        pp_features = [f for f in self.feature_columns if 'lag' in f and f.startswith('pp')]
        team_features = [f for f in self.feature_columns if 'lag' in f and 
                        any(team_f in f for team_f in ['wins', 'losses', 'goals_for', 'goals_against'])]
        experience_features = [f for f in self.feature_columns if 'years_played' in f or 'rookie' in f or 'prime' in f or 'veteran' in f]
        covid_features = [f for f in self.feature_columns if 'covid' in f]
        interaction_features = [f for f in self.feature_columns if '_x_' in f]
        engineered_features = [f for f in self.feature_columns if 'hist' in f or 'trend' in f]
        
        print(f"\nDEFENSEMEN FEATURE BREAKDOWN:")
        print("-" * 65)
        print(f"Individual lagged features: {len(individual_features)}")
        print(f"Power play lagged features: {len(pp_features)}")
        print(f"Team lagged features: {len(team_features)}")
        print(f"Experience features: {len(experience_features)}")
        print(f"COVID control features: {len(covid_features)}")
        print(f"Interaction features: {len(interaction_features)}")
        print(f"Engineered features: {len(engineered_features)}")
        
        # Get feature matrix and targets
        X = df[self.feature_columns].copy()
        y_points = df[self.target_points].copy()
        y_plusminus = df[self.target_plusminus].copy()
        
        print(f"\nBefore missing data removal: {len(X)} observations")
        
        # Force conversion to numeric
        for col in X.columns:
            X[col] = pd.to_numeric(X[col], errors='coerce')
        
        # Handle missing data
        core_features = [f for f in X.columns if any(core in f for core in ['goals_lag', 'assists_lag', 'plus_minus_lag'])]
        
        if core_features:
            missing_mask = X[core_features].isnull().all(axis=1) | y_points.isnull() | y_plusminus.isnull()
        else:
            missing_mask = X.isnull().all(axis=1) | y_points.isnull() | y_plusminus.isnull()
        
        if missing_mask.any():
            X_clean = X[~missing_mask]
            y_points_clean = y_points[~missing_mask]
            y_plusminus_clean = y_plusminus[~missing_mask]
            print(f"Removed {missing_mask.sum()} rows with missing core data")
        else:
            X_clean = X
            y_points_clean = y_points
            y_plusminus_clean = y_plusminus
        
        # Fill remaining missing values
        X_clean = X_clean.fillna(0)
        
        print(f"After missing data handling: {len(X_clean)} observations")
        print(f"Final feature matrix shape: {X_clean.shape}")
        
        return X_clean, y_points_clean, y_plusminus_clean
    
    def train_dual_models(self, X: pd.DataFrame, y_points: pd.Series, y_plusminus: pd.Series, 
                         model_type: str = 'random_forest') -> Dict[str, Any]:
        """
        Train dual models for defensemen: points per game and plus/minus.
        
        Args:
            X: Feature matrix
            y_points: Points per game target
            y_plusminus: Plus/minus per game target
            model_type: Type of model to train
            
        Returns:
            Dictionary containing results from both models
        """
        print(f"\nTraining dual defensemen models ({model_type}):")
        print(f"  Training data shape: {X.shape}")
        print(f"  Targets: {self.target_points} and {self.target_plusminus}")
        
        if len(X) < 20:
            raise ValueError(f"Insufficient data for training: {len(X)} observations")
        
        results = {}
        
        # Train Points Model
        print(f"\n  Training POINTS model...")
        results['points'] = self._train_single_model(X, y_points, model_type, 'points')
        
        # Train Plus/Minus Model
        print(f"\n  Training PLUS/MINUS model...")
        results['plusminus'] = self._train_single_model(X, y_plusminus, model_type, 'plusminus')
        
        # Combined results summary
        results['combined'] = {
            'model_type': model_type,
            'points_r2': results['points']['r2'],
            'plusminus_r2': results['plusminus']['r2'],
            'points_rmse': results['points']['rmse'],
            'plusminus_rmse': results['plusminus']['rmse'],
            'n_train': results['points']['n_train'],
            'n_features_points': results['points']['n_features_selected'],
            'n_features_plusminus': results['plusminus']['n_features_selected']
        }
        
        print(f"\n  DUAL MODEL SUMMARY:")
        print(f"    Points R²: {results['points']['r2']:.3f}, RMSE: {results['points']['rmse']:.4f}")
        print(f"    Plus/Minus R²: {results['plusminus']['r2']:.3f}, RMSE: {results['plusminus']['rmse']:.4f}")
        
        return results
    
    def _train_single_model(self, X: pd.DataFrame, y: pd.Series, model_type: str, target_name: str) -> Dict[str, Any]:
        """Train a single model for either points or plus/minus."""
        # Feature selection for this target
        if self.use_feature_selection and len(self.feature_columns) > 20:
            k_features = min(40, max(12, len(self.feature_columns) // 4))
            feature_selector = SelectKBest(score_func=f_regression, k=k_features)
            X_selected = feature_selector.fit_transform(X, y)
            selected_features = X.columns[feature_selector.get_support()].tolist()
            X = pd.DataFrame(X_selected, columns=selected_features, index=X.index)
            
            # Store feature selector
            if target_name == 'points':
                self.feature_selector_points = feature_selector
                self.selected_features_points = selected_features
            else:
                self.feature_selector_plusminus = feature_selector
                self.selected_features_plusminus = selected_features
            
            print(f"    Selected {len(selected_features)} features for {target_name}")
        else:
            if target_name == 'points':
                self.selected_features_points = self.feature_columns
            else:
                self.selected_features_plusminus = self.feature_columns
        
        # Split data
        test_size = min(0.25, max(0.15, 40/len(X)))
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
        
        # Get model configuration
        models = self._get_enhanced_models()
        if model_type not in models:
            raise ValueError(f"Unknown model type: {model_type}")
        
        model_config = models[model_type]
        
        # Scale features for linear models
        scaler = self.scaler_points if target_name == 'points' else self.scaler_plusminus
        
        if model_type in ['ridge', 'lasso', 'elastic_net']:
            X_train_scaled = scaler.fit_transform(X_train)
            X_test_scaled = scaler.transform(X_test)
            X_train_final = X_train_scaled
            X_test_final = X_test_scaled
        else:
            X_train_final = X_train
            X_test_final = X_test
        
        # Hyperparameter tuning
        cv_folds = min(5, max(3, len(X_train) // 30))
        
        if model_config['search_type'] == 'randomized':
            search = RandomizedSearchCV(
                estimator=model_config['model'],
                param_distributions=model_config['params'],
                n_iter=model_config['n_iter'],
                cv=cv_folds,
                scoring='r2',
                n_jobs=-1,
                random_state=42
            )
        else:
            search = GridSearchCV(
                estimator=model_config['model'],
                param_grid=model_config['params'],
                cv=cv_folds,
                scoring='r2',
                n_jobs=-1
            )
        
        search.fit(X_train_final, y_train)
        
        # Store model
        if target_name == 'points':
            self.model_points = search.best_estimator_
            self.best_params_points = search.best_params_
        else:
            self.model_plusminus = search.best_estimator_
            self.best_params_plusminus = search.best_params_
        
        # Predictions and metrics
        y_pred = search.best_estimator_.predict(X_test_final)
        
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)
        r2 = r2_score(y_test, y_pred)
        
        train_score = search.best_estimator_.score(X_train_final, y_train)
        test_score = r2
        overfitting_ratio = (train_score - test_score) / train_score if train_score > 0 else 0
        
        results = {
            'mae': mae, 'mse': mse, 'rmse': rmse, 'r2': r2,
            'train_r2': train_score, 'test_r2': test_score,
            'overfitting_ratio': overfitting_ratio,
            'cv_mean': search.best_score_,
            'y_test': y_test, 'y_pred': y_pred,
            'model_type': model_type,
            'target_name': target_name,
            'best_params': search.best_params_,
            'n_train': len(X_train), 'n_test': len(X_test),
            'n_features_selected': len(X.columns)
        }
        
        return results
    
    def _get_enhanced_models(self) -> Dict[str, Any]:
        """Enhanced model configurations for defensemen."""
        models = {
            'random_forest': {
                'model': RandomForestRegressor(random_state=42, n_jobs=-1),
                'params': {
                    'n_estimators': [150, 250],
                    'max_depth': [12, 18],
                    'min_samples_split': [15, 25],
                    'min_samples_leaf': [8, 12],
                    'max_features': ['sqrt', 0.4]
                },
                'search_type': 'randomized',
                'n_iter': 8
            },
            'gradient_boosting': {
                'model': GradientBoostingRegressor(random_state=42),
                'params': {
                    'n_estimators': [150, 250],
                    'max_depth': [4, 6],
                    'learning_rate': [0.05, 0.1],
                    'subsample': [0.8, 0.9],
                    'min_samples_split': [15, 25],
                    'max_features': ['sqrt', 0.4]
                },
                'search_type': 'randomized',
                'n_iter': 10
            },
            'ridge': {
                'model': Ridge(random_state=42),
                'params': {
                    'alpha': [10.0, 50.0, 100.0, 500.0]
                },
                'search_type': 'grid'
            },
            'lasso': {
                'model': Lasso(random_state=42, max_iter=3000),
                'params': {
                    'alpha': [0.1, 0.5, 1.0, 5.0]
                },
                'search_type': 'grid'
            },
            'elastic_net': {
                'model': ElasticNet(random_state=42, max_iter=3000),
                'params': {
                    'alpha': [0.1, 1.0, 5.0],
                    'l1_ratio': [0.3, 0.5, 0.7]
                },
                'search_type': 'grid'
            }
        }
        return models
    
    def predict_season_with_combined_ranking(self, df_full: pd.DataFrame, target_year: int) -> pd.DataFrame:
        """
        Predict both points and plus/minus for defensemen and create comprehensive rankings.
        
        Args:
            df_full: Complete dataset including target year
            target_year: Year to predict (e.g., 2024 for 2024-2025 season)
            
        Returns:
            DataFrame with comprehensive predictions and rankings for all categories
        """
        if self.model_points is None or self.model_plusminus is None:
            raise ValueError("Both models must be trained first")
        
        # Get target year data
        target_data = df_full[df_full['year'] == target_year].copy()
        
        if len(target_data) == 0:
            raise ValueError(f"No defensemen data found for year {target_year}")
        
        print(f"\nPredicting {target_year} season for defensemen with comprehensive ranking:")
        print(f"  Defensemen to predict: {len(target_data)}")
        
        # Prepare features
        X_pred, _, _ = self.prepare_features(target_data)
        
        print(f"  Defensemen with complete feature data: {len(X_pred)}")
        
        # Apply feature selection for points model
        if self.feature_selector_points is not None:
            X_pred_points = X_pred[self.selected_features_points]
        else:
            X_pred_points = X_pred
        
        # Apply feature selection for plus/minus model
        if self.feature_selector_plusminus is not None:
            X_pred_plusminus = X_pred[self.selected_features_plusminus]
        else:
            X_pred_plusminus = X_pred
        
        # Scale features if needed
        if hasattr(self.scaler_points, 'transform') and self.model_points.__class__.__name__ in ['Ridge', 'Lasso', 'ElasticNet']:
            X_pred_points_final = self.scaler_points.transform(X_pred_points)
        else:
            X_pred_points_final = X_pred_points
        
        if hasattr(self.scaler_plusminus, 'transform') and self.model_plusminus.__class__.__name__ in ['Ridge', 'Lasso', 'ElasticNet']:
            X_pred_plusminus_final = self.scaler_plusminus.transform(X_pred_plusminus)
        else:
            X_pred_plusminus_final = X_pred_plusminus
        
        # Make predictions
        predicted_ppg = self.model_points.predict(X_pred_points_final)
        predicted_pm_pg = self.model_plusminus.predict(X_pred_plusminus_final)
        
        # Create results dataframe
        results_df = target_data.loc[X_pred.index].copy()
        results_df['predicted_ppg'] = predicted_ppg
        results_df['predicted_pm_per_game'] = predicted_pm_pg
        
        # Get actual games played
        results_df['actual_games'] = results_df['games_played'].fillna(0)
        
        # COMPREHENSIVE PREDICTIONS: Points (actual games and 82 games)
        results_df['predicted_points_actual'] = results_df['predicted_ppg'] * results_df['actual_games']
        results_df['predicted_points_82games'] = results_df['predicted_ppg'] * 82
        
        # COMPREHENSIVE PREDICTIONS: Plus/Minus (actual games and 82 games)
        results_df['predicted_pm_actual'] = results_df['predicted_pm_per_game'] * results_df['actual_games']
        results_df['predicted_pm_82games'] = results_df['predicted_pm_per_game'] * 82
        
        # COMPREHENSIVE PREDICTIONS: Combined (actual games and 82 games)
        results_df['predicted_combined_actual'] = results_df['predicted_points_actual'] + results_df['predicted_pm_actual']
        results_df['predicted_combined_82games'] = results_df['predicted_points_82games'] + results_df['predicted_pm_82games']
        
        # ACTUAL VALUES for comparison
        if 'total_points' in results_df.columns:
            results_df['actual_points'] = results_df['total_points']
        else:
            results_df['actual_points'] = results_df.get('goals', 0) + results_df.get('assists', 0)
        
        if 'total_plus_minus' in results_df.columns:
            results_df['actual_pm'] = results_df['total_plus_minus']
        else:
            results_df['actual_pm'] = 0
        
        results_df['actual_combined'] = results_df['actual_points'] + results_df['actual_pm']
        
        # Sort by combined score (82 games) for ranking
        results_df = results_df.sort_values('predicted_combined_82games', ascending=False)
        
        # Return comprehensive columns
        return_cols = ['player_name', 'actual_games',
                      'predicted_points_actual', 'predicted_points_82games', 
                      'predicted_pm_actual', 'predicted_pm_82games',
                      'predicted_combined_actual', 'predicted_combined_82games',
                      'actual_points', 'actual_pm', 'actual_combined']
        
        return results_df[return_cols].reset_index(drop=True)

    def plot_dual_results(self, results: Dict[str, Any], save_path: str = None):
        """
        Create comprehensive plots for dual defensemen model results.
        
        Args:
            results: Dictionary containing dual model results
            save_path: Optional path to save the plot
        """
        fig, axes = plt.subplots(3, 2, figsize=(16, 18))
        
        # Points Model Results (Top Row)
        points_results = results['points']
        
        # Panel 1: Points Actual vs Predicted
        axes[0, 0].scatter(points_results['y_test'], points_results['y_pred'], alpha=0.6, color='blue')
        min_val, max_val = points_results['y_test'].min(), points_results['y_test'].max()
        axes[0, 0].plot([min_val, max_val], [min_val, max_val], 'r--', lw=2)
        axes[0, 0].set_xlabel('Actual Points Per Game')
        axes[0, 0].set_ylabel('Predicted Points Per Game')
        axes[0, 0].set_title(f'Defensemen Points Prediction\nR² = {points_results["r2"]:.3f}')
        axes[0, 0].grid(True, alpha=0.3)
        
        # Panel 2: Points Residuals
        residuals_points = points_results['y_test'] - points_results['y_pred']
        axes[0, 1].scatter(points_results['y_pred'], residuals_points, alpha=0.6, color='green')
        axes[0, 1].axhline(y=0, color='r', linestyle='--')
        axes[0, 1].set_xlabel('Predicted Points Per Game')
        axes[0, 1].set_ylabel('Residuals')
        axes[0, 1].set_title('Points Residual Plot')
        axes[0, 1].grid(True, alpha=0.3)
        
        # Plus/Minus Model Results (Middle Row)
        pm_results = results['plusminus']
        
        # Panel 3: Plus/Minus Actual vs Predicted
        axes[1, 0].scatter(pm_results['y_test'], pm_results['y_pred'], alpha=0.6, color='red')
        min_val, max_val = pm_results['y_test'].min(), pm_results['y_test'].max()
        axes[1, 0].plot([min_val, max_val], [min_val, max_val], 'r--', lw=2)
        axes[1, 0].set_xlabel('Actual Plus/Minus Per Game')
        axes[1, 0].set_ylabel('Predicted Plus/Minus Per Game')
        axes[1, 0].set_title(f'Defensemen Plus/Minus Prediction\nR² = {pm_results["r2"]:.3f}')
        axes[1, 0].grid(True, alpha=0.3)
        
        # Panel 4: Plus/Minus Residuals
        residuals_pm = pm_results['y_test'] - pm_results['y_pred']
        axes[1, 1].scatter(pm_results['y_pred'], residuals_pm, alpha=0.6, color='orange')
        axes[1, 1].axhline(y=0, color='r', linestyle='--')
        axes[1, 1].set_xlabel('Predicted Plus/Minus Per Game')
        axes[1, 1].set_ylabel('Residuals')
        axes[1, 1].set_title('Plus/Minus Residual Plot')
        axes[1, 1].grid(True, alpha=0.3)
        
        # Combined Results (Bottom Row)
        
        # Panel 5: Model Performance Comparison
        metrics = ['Points R²', 'Plus/Minus R²']
        values = [points_results['r2'], pm_results['r2']]
        colors_perf = ['blue', 'red']
        
        bars = axes[2, 0].bar(metrics, values, alpha=0.7, color=colors_perf)
        axes[2, 0].set_ylabel('R² Score')
        axes[2, 0].set_title('Dual Model Performance Comparison')
        axes[2, 0].set_ylim(0, max(values) * 1.1)
        axes[2, 0].grid(True, alpha=0.3)
        
        # Add value labels on bars
        for bar, value in zip(bars, values):
            axes[2, 0].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                           f'{value:.3f}', ha='center', va='bottom', fontsize=12)
        
        # Panel 6: Model Configuration Summary
        axes[2, 1].axis('off')
        config_text = f"Defensemen Dual Model v1.0\n"
        config_text += f"Targets: Points + Plus/Minus Per Game\n"
        config_text += f"Model: {results['combined']['model_type']}\n"
        config_text += f"Training samples: {results['combined']['n_train']}\n\n"
        
        config_text += "Points Model:\n"
        config_text += f"  R²: {results['points']['r2']:.3f}\n"
        config_text += f"  RMSE: {results['points']['rmse']:.4f}\n"
        config_text += f"  Features: {results['combined']['n_features_points']}\n\n"
        
        config_text += "Plus/Minus Model:\n"
        config_text += f"  R²: {results['plusminus']['r2']:.3f}\n"
        config_text += f"  RMSE: {results['plusminus']['rmse']:.4f}\n"
        config_text += f"  Features: {results['combined']['n_features_plusminus']}\n\n"
        
        config_text += "Key Features:\n"
        config_text += "• Dual target modeling\n"
        config_text += "• Defensemen-specific metrics\n"
        config_text += "• Experience interactions\n"
        config_text += "• Combined performance ranking\n"
        
        axes[2, 1].text(0.1, 0.9, config_text, transform=axes[2, 1].transAxes, 
                       fontsize=9, verticalalignment='top', fontfamily='monospace')
        axes[2, 1].set_title('Dual Model Configuration')
        
        plt.tight_layout()
        
        if save_path:
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Dual model plot saved to: {save_path}")
        else:
            plt.show()
        
        plt.close()
    
    def get_dual_feature_importance(self, top_n: int = 25) -> Dict[str, pd.DataFrame]:
        """
        Get feature importance analysis for both points and plus/minus models.
        
        Args:
            top_n: Number of top features to return for each model
            
        Returns:
            Dictionary with 'points' and 'plusminus' feature importance DataFrames
        """
        if self.model_points is None or self.model_plusminus is None:
            raise ValueError("Both models must be trained first")
        
        results = {}
        
        # Points model feature importance
        results['points'] = self._get_single_model_importance(
            self.model_points, self.selected_features_points, 'points', top_n
        )
        
        # Plus/minus model feature importance
        results['plusminus'] = self._get_single_model_importance(
            self.model_plusminus, self.selected_features_plusminus, 'plusminus', top_n
        )
        
        return results
    
    def _get_single_model_importance(self, model, feature_names, model_name, top_n):
        """Get feature importance for a single model."""
        # Get importance values
        if hasattr(model, 'feature_importances_'):
            importance = model.feature_importances_
        else:
            importance = np.abs(model.coef_)
        
        importance_df = pd.DataFrame({
            'feature': feature_names,
            'importance': importance,
            'model': model_name
        }).sort_values('importance', ascending=False)
        
        # Enhanced categorization for defensemen features
        def categorize_defensive_feature(feature_name):
            if 'covid' in feature_name.lower():
                return "COVID"
            elif 'years_played' in feature_name or 'rookie' in feature_name or 'prime' in feature_name or 'veteran' in feature_name:
                return "EXPERIENCE"
            elif '_x_' in feature_name:
                return "INTERACTION"
            elif 'plus_minus' in feature_name or 'pm_' in feature_name:
                return "PLUS_MINUS"
            elif any(team_indicator in feature_name.lower() for team_indicator in ['wins', 'losses', 'goals_for', 'goals_against']):
                return "TEAM"
            elif feature_name.startswith('pp'):
                return "POWERPLAY"
            elif any(metric in feature_name for metric in ['goals', 'assists', 'points', 'shots']):
                return "OFFENSIVE"
            elif 'time_on_ice' in feature_name or 'toi' in feature_name:
                return "ICE_TIME"
            else:
                return "OTHER"
        
        importance_df['category'] = importance_df['feature'].apply(categorize_defensive_feature)
        
        return importance_df.head(top_n)
    
    def plot_dual_feature_importance(self, importance_results: Dict[str, pd.DataFrame], save_path: str = None):
        """
        Plot feature importance for both models side by side.
        
        Args:
            importance_results: Dictionary with points and plus/minus importance DataFrames
            save_path: Optional path to save the plot
        """
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 10))
        
        # Enhanced color scheme for defensemen categories
        colors = {
            'OFFENSIVE': 'blue', 
            'PLUS_MINUS': 'red',
            'TEAM': 'green', 
            'POWERPLAY': 'orange',
            'EXPERIENCE': 'purple',
            'INTERACTION': 'brown',
            'COVID': 'pink',
            'ICE_TIME': 'cyan',
            'OTHER': 'gray'
        }
        
        # Points model feature importance
        points_df = importance_results['points']
        bar_colors_points = [colors.get(cat, 'gray') for cat in points_df['category']]
        
        bars1 = ax1.barh(range(len(points_df)), points_df['importance'], 
                        color=bar_colors_points, alpha=0.7)
        ax1.set_yticks(range(len(points_df)))
        ax1.set_yticklabels([f.replace('_lag', '_l').replace('_hist_avg', '_avg')[:30] 
                            for f in points_df['feature']], fontsize=8)
        ax1.set_xlabel('Importance')
        ax1.set_title(f'Points Model - Top {len(points_df)} Features')
        ax1.invert_yaxis()
        
        # Plus/minus model feature importance
        pm_df = importance_results['plusminus']
        bar_colors_pm = [colors.get(cat, 'gray') for cat in pm_df['category']]
        
        bars2 = ax2.barh(range(len(pm_df)), pm_df['importance'], 
                        color=bar_colors_pm, alpha=0.7)
        ax2.set_yticks(range(len(pm_df)))
        ax2.set_yticklabels([f.replace('_lag', '_l').replace('_hist_avg', '_avg')[:30] 
                            for f in pm_df['feature']], fontsize=8)
        ax2.set_xlabel('Importance')
        ax2.set_title(f'Plus/Minus Model - Top {len(pm_df)} Features')
        ax2.invert_yaxis()
        
        # Combined legend
        from matplotlib.patches import Patch
        legend_elements = [
            Patch(facecolor='blue', alpha=0.7, label='Offensive'),
            Patch(facecolor='red', alpha=0.7, label='Plus/Minus'),
            Patch(facecolor='green', alpha=0.7, label='Team'),
            Patch(facecolor='orange', alpha=0.7, label='PowerPlay'),
            Patch(facecolor='purple', alpha=0.7, label='Experience'),
            Patch(facecolor='brown', alpha=0.7, label='Interaction'),
            Patch(facecolor='pink', alpha=0.7, label='COVID'),
            Patch(facecolor='cyan', alpha=0.7, label='Ice Time'),
            Patch(facecolor='gray', alpha=0.7, label='Other')
        ]
        fig.legend(handles=legend_elements, loc='upper center', bbox_to_anchor=(0.5, 0.02), 
                  ncol=5, fontsize=10)
        
        plt.suptitle('Defensemen Dual Model Feature Importance Comparison', fontsize=14, y=0.95)
        plt.tight_layout()
        plt.subplots_adjust(bottom=0.1)
        
        if save_path:
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Feature importance plot saved to: {save_path}")
        else:
            plt.show()
        
        plt.close()

def main():
    """
    Main function for Defensemen Dual Performance Predictor v1.0.
    
    Features:
    - Dual model training for points and plus/minus
    - Defensemen-only analysis
    - Combined performance ranking
    - Experience and COVID controls
    - Enhanced feature engineering for defensive metrics
    """
    
    print("Defensemen Dual Performance Predictor v1.0 - Points + Plus/Minus Modeling")
    print("=" * 100)
    print(f"Run started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"DUAL TARGET APPROACH: Points per game + Plus/minus per game for defensemen")
    print(f"COMBINED RANKING: Total impact = predicted points + predicted plus/minus")
    print(f"PRIMARY DATA SOURCE: data_output/skater_team_data.csv (defensemen only)")
    
    # Setup paths and find CSV file
    try:
        csv_path = find_csv_file()
        plots_dir, results_dir = setup_output_directories()
    except FileNotFoundError as e:
        print(f"\nERROR: {e}")
        print("Please ensure your merged player-team CSV file is accessible and try again.")
        return
    except Exception as e:
        print(f"\nERROR setting up paths: {e}")
        return
    
    # Setup output file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(results_dir, f'defensemen_dual_performance_prediction_v1_{timestamp}.txt')
    
    # Setup output manager
    output_manager = OutputManager(output_file)
    sys.stdout = output_manager
    
    try:
        print("Defensemen Dual Performance Predictor v1.0")
        print("=" * 100)
        print(f"Run started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Data file: {csv_path}")
        print(f"Results will be saved to: {output_file}")
        
        # TRAINING A: All data with dual models
        print(f"\n{'='*100}")
        print("TRAINING A: ALL DEFENSEMEN DATA WITH DUAL MODELS (v1.0)")
        print('='*100)
        
        best_results_all = None
        best_config_all = None
        best_score_all = -1
        
        # Test configurations
        configs = [
            {'lag_years': 2, 'min_training_year': None, 'use_feature_selection': True},
            {'lag_years': 1, 'min_training_year': None, 'use_feature_selection': True},
            {'lag_years': 3, 'min_training_year': None, 'use_feature_selection': True}
        ]
        
        for config in configs:
            print(f"\nTesting {config['lag_years']}-year lags (ALL DEFENSEMEN DATA)")
            print('-' * 80)
            
            try:
                predictor = DefensemenDualPerformancePredictor(**config)
                
                print("Loading and enhancing defensemen data...")
                df = predictor.load_data(csv_path)
                
                print("Creating lag features for defensemen...")
                df_with_lags = predictor.create_lag_features(df)
                
                print("Engineering defensemen-specific features...")
                df_engineered = predictor.engineer_features(df_with_lags)
                
                print("Preparing dual target feature set...")
                X, y_points, y_plusminus = predictor.prepare_features(df_engineered)
                
                print(f"Final dataset: {len(X)} observations, {X.shape[1] if len(X) > 0 else 0} features")
                
                if len(X) < 50:
                    print(f"Insufficient data: {len(X)} observations")
                    continue
                
                # Test models
                models = ['random_forest', 'ridge', 'gradient_boosting', 'lasso', 'elastic_net']
                
                for model_type in models:
                    try:
                        print(f"\n  Testing {model_type} for dual targets...")
                        results = predictor.train_dual_models(X, y_points, y_plusminus, model_type=model_type)
                        
                        # Combined score (average of both R² scores)
                        combined_score = (results['points']['r2'] + results['plusminus']['r2']) / 2
                        
                        if combined_score > best_score_all:
                            best_score_all = combined_score
                            best_results_all = results
                            best_config_all = {**config, 'model_type': model_type, 'predictor': predictor}
                            print(f"    New best dual model: {model_type} with combined score = {combined_score:.3f}")
                            
                    except Exception as e:
                        print(f"    Error with {model_type}: {e}")
                        continue
                        
            except Exception as e:
                print(f"Error with configuration {config}: {e}")
                continue
        
        # TRAINING B: Predict 2024-2025 with dual targets
        print(f"\n{'='*100}")
        print("TRAINING B: PREDICT 2024-2025 DEFENSEMEN WITH DUAL TARGETS (v1.0)")
        print('='*100)
        
        best_results_pred = None
        best_config_pred = None
        best_score_pred = -1
        best_predictions = None
        
        for config in configs:
            print(f"\nTesting {config['lag_years']}-year lags (EXCLUDING 2024-2025)")
            print('-' * 80)
            
            try:
                predictor = DefensemenDualPerformancePredictor(**config)
                
                print("Loading and enhancing defensemen data...")
                df_full = predictor.load_data(csv_path)
                
                # Split data: exclude 2024-2025 for training
                df_train = df_full[df_full['year'] != 2024].copy()
                
                print(f"Full defensemen dataset: {len(df_full)} observations")
                print(f"Training dataset (no 2024-2025): {len(df_train)} observations")
                print(f"2024-2025 defensemen data: {len(df_full[df_full['year'] == 2024])} observations")
                
                print("Creating lag features for defensemen...")
                df_with_lags = predictor.create_lag_features(df_train)
                
                print("Engineering defensemen-specific features...")
                df_engineered = predictor.engineer_features(df_with_lags)
                
                print("Preparing dual target feature set...")
                X, y_points, y_plusminus = predictor.prepare_features(df_engineered)
                
                print(f"Final training dataset: {len(X)} observations")
                
                if len(X) < 50:
                    print(f"Insufficient training data: {len(X)} observations")
                    continue
                
                # Test models
                models = ['random_forest', 'ridge', 'gradient_boosting', 'lasso', 'elastic_net']
                
                for model_type in models:
                    try:
                        print(f"\n  Testing {model_type} for dual prediction...")
                        results = predictor.train_dual_models(X, y_points, y_plusminus, model_type=model_type)
                        
                        # Combined score
                        combined_score = (results['points']['r2'] + results['plusminus']['r2']) / 2
                        
                        if combined_score > best_score_pred:
                            best_score_pred = combined_score
                            best_results_pred = results
                            best_config_pred = {**config, 'model_type': model_type, 'predictor': predictor}
                            print(f"    New best prediction model: {model_type} with combined score = {combined_score:.3f}")
                            
                            # Generate combined predictions
                            try:
                                print("    Generating 2024-2025 dual predictions...")
                                df_full_with_lags = predictor.create_lag_features(df_full)
                                df_full_engineered = predictor.engineer_features(df_full_with_lags)
                                predictions = predictor.predict_season_with_combined_ranking(df_full_engineered, 2024)
                                best_predictions = predictions
                                print(f"    Successfully generated predictions for {len(predictions)} defensemen")
                            except Exception as e:
                                print(f"    Error generating predictions: {e}")
                                best_predictions = None
                            
                    except Exception as e:
                        print(f"    Error with {model_type}: {e}")
                        continue
                        
            except Exception as e:
                print(f"Error with configuration {config}: {e}")
                continue
        
        # Display comprehensive results
        print(f"\n{'='*100}")
        print("DEFENSEMEN DUAL MODEL RESULTS SUMMARY (v1.0)")
        print('='*100)
        
        if best_results_all:
            print(f"\nTRAINING A - ALL DEFENSEMEN DATA (DUAL MODELS v1.0):")
            print(f"  Best configuration: {best_config_all['lag_years']}-year lags, {best_config_all['model_type']}")
            print(f"  Points Model - R²: {best_results_all['points']['r2']:.3f}, RMSE: {best_results_all['points']['rmse']:.4f}")
            print(f"  Plus/Minus Model - R²: {best_results_all['plusminus']['r2']:.3f}, RMSE: {best_results_all['plusminus']['rmse']:.4f}")
            print(f"  Combined Score: {best_score_all:.3f}")
            print(f"  Features (Points): {best_results_all['combined']['n_features_points']}")
            print(f"  Features (Plus/Minus): {best_results_all['combined']['n_features_plusminus']}")
            
            # Generate and save diagnostic plot
            plot_filename = os.path.join(plots_dir, f'defensemen_dual_model_v1_all_data_{timestamp}.png')
            try:
                best_config_all['predictor'].plot_dual_results(best_results_all, save_path=plot_filename)
                print(f"All data plot saved to: {plot_filename}")
            except Exception as e:
                print(f"Could not generate plot: {e}")
            
            # Feature importance analysis for both models
            print(f"\nDUAL MODEL FEATURE IMPORTANCE ANALYSIS:")
            print("-" * 90)
            try:
                importance_results = best_config_all['predictor'].get_dual_feature_importance(20)
                
                print(f"\nTop 20 Most Important Features - POINTS MODEL:")
                print("-" * 80)
                for idx, row in importance_results['points'].iterrows():
                    print(f"{idx+1:2d}. {row['feature']:45} {row['importance']:.4f} ({row['category']})")
                
                print(f"\nTop 20 Most Important Features - PLUS/MINUS MODEL:")
                print("-" * 80)
                for idx, row in importance_results['plusminus'].iterrows():
                    print(f"{idx+1:2d}. {row['feature']:45} {row['importance']:.4f} ({row['category']})")
                
                # Generate feature importance plot
                importance_plot_filename = os.path.join(plots_dir, f'defensemen_feature_importance_v1_all_data_{timestamp}.png')
                best_config_all['predictor'].plot_dual_feature_importance(importance_results, save_path=importance_plot_filename)
                print(f"Feature importance plot saved to: {importance_plot_filename}")
                
            except Exception as e:
                print(f"Could not display feature importance: {e}")
        
        if best_results_pred and best_predictions is not None:
            print(f"\nTRAINING B - PREDICT 2024-2025 DEFENSEMEN (DUAL v1.0):")
            print(f"  Best configuration: {best_config_pred['lag_years']}-year lags, {best_config_pred['model_type']}")
            print(f"  Points Model - R²: {best_results_pred['points']['r2']:.3f}, RMSE: {best_results_pred['points']['rmse']:.4f}")
            print(f"  Plus/Minus Model - R²: {best_results_pred['plusminus']['r2']:.3f}, RMSE: {best_results_pred['plusminus']['rmse']:.4f}")
            print(f"  Combined Prediction Score: {best_score_pred:.3f}")
            
            # Generate and save prediction diagnostic plot
            plot_filename = os.path.join(plots_dir, f'defensemen_dual_model_v1_prediction_{timestamp}.png')
            try:
                best_config_pred['predictor'].plot_dual_results(best_results_pred, save_path=plot_filename)
                print(f"Prediction plot saved to: {plot_filename}")
            except Exception as e:
                print(f"Could not generate prediction plot: {e}")
            
            # Feature importance analysis for prediction models
            print(f"\nPREDICTION MODEL FEATURE IMPORTANCE ANALYSIS:")
            print("-" * 90)
            try:
                importance_results_pred = best_config_pred['predictor'].get_dual_feature_importance(15)
                
                print(f"\nTop 15 Most Important Features - POINTS PREDICTION MODEL:")
                print("-" * 80)
                for idx, row in importance_results_pred['points'].iterrows():
                    print(f"{idx+1:2d}. {row['feature']:45} {row['importance']:.4f} ({row['category']})")
                
                print(f"\nTop 15 Most Important Features - PLUS/MINUS PREDICTION MODEL:")
                print("-" * 80)
                for idx, row in importance_results_pred['plusminus'].iterrows():
                    print(f"{idx+1:2d}. {row['feature']:45} {row['importance']:.4f} ({row['category']})")
                
                # Generate feature importance plot for prediction models
                importance_plot_filename_pred = os.path.join(plots_dir, f'defensemen_feature_importance_v1_prediction_{timestamp}.png')
                best_config_pred['predictor'].plot_dual_feature_importance(importance_results_pred, save_path=importance_plot_filename_pred)
                print(f"Prediction feature importance plot saved to: {importance_plot_filename_pred}")
                
            except Exception as e:
                print(f"Could not display prediction feature importance: {e}")
            
            # COMPREHENSIVE RANKING OUTPUT
            print(f"\nTOP 50 DEFENSEMEN - 2024-2025 COMPREHENSIVE PERFORMANCE RANKING:")
            print("=" * 170)
            print("PREDICTIONS (Actual Games vs 82 Games) and ACTUAL VALUES:")
            print(f"{'Rank':<4} {'Player Name':<25} {'Games':<6} {'Pts(Act)':<9} {'Pts(82)':<8} {'PM(Act)':<8} {'PM(82)':<7} "
                  f"{'Comb(Act)':<9} {'Comb(82)':<9} {'A_Pts':<6} {'A_PM':<6} {'A_Comb':<7}")
            print("-" * 170)
            
            for idx, row in best_predictions.head(50).iterrows():
                actual_pts = row['actual_points'] if not pd.isna(row['actual_points']) else 'N/A'
                actual_pm = row['actual_pm'] if not pd.isna(row['actual_pm']) else 'N/A'
                actual_combined = row['actual_combined'] if not pd.isna(row['actual_combined']) else 'N/A'
                
                print(f"{idx+1:<4} {row['player_name']:<25} {row['actual_games']:<6.0f} "
                      f"{row['predicted_points_actual']:<9.1f} {row['predicted_points_82games']:<8.1f} "
                      f"{row['predicted_pm_actual']:<8.1f} {row['predicted_pm_82games']:<7.1f} "
                      f"{row['predicted_combined_actual']:<9.1f} {row['predicted_combined_82games']:<9.1f} "
                      f"{actual_pts:<6} {actual_pm:<6} {actual_combined:<7}")
            
            # Legend for the comprehensive output
            print(f"\nLEGEND:")
            print(f"Pts(Act) = Predicted Points for Actual Games | Pts(82) = Predicted Points for 82 Games")
            print(f"PM(Act) = Predicted Plus/Minus for Actual Games | PM(82) = Predicted Plus/Minus for 82 Games") 
            print(f"Comb(Act) = Combined Score for Actual Games | Comb(82) = Combined Score for 82 Games")
            print(f"A_Pts = Actual Points | A_PM = Actual Plus/Minus | A_Comb = Actual Combined Score")
        
        # Summary for v1.0
        print(f"\n{'='*100}")
        print("NEW FEATURES IN DEFENSEMEN MODEL VERSION 1.0:")
        print('='*100)
        print("• DUAL TARGET MODELING: Separate models for points and plus/minus")
        print("• DEFENSEMEN FOCUS: Position = D only, removes all forwards")
        print("• COMBINED RANKING: Total impact = predicted points + predicted plus/minus")
        print("• DEFENSIVE METRICS: Plus/minus per game as key evaluation metric")
        print("• EXPERIENCE FEATURES: Years played with defensive career curve modeling")
        print("• COVID CONTROLS: Special handling for 2019-2020 and 2020-2021 seasons")  
        print("• ICE TIME EMPHASIS: Higher default TOI for defensemen (20 min vs 15 min)")
        print("• DEFENSIVE INTERACTIONS: Experience × defensive performance cross-effects")
        print("• DUAL PROJECTIONS: Both actual games and 82-game projections for each metric")
        print("• COMPREHENSIVE EVALUATION: Complete defensemen performance assessment")
        
        print(f"\nRun completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Results saved to: {output_file}")
    
    finally:
        # Restore stdout and close file
        sys.stdout = output_manager.terminal
        output_manager.close()

if __name__ == "__main__":
    main()