# Date: August 23, 2025
# Author: Julian di Giovanni w/Claude.ai - Version 6.0 Points Per Game Edition - DATA LEAKAGE FIXED
# Version: 6.0 - Points Per Game Prediction with Enhanced Team Context + Experience Features - COMPREHENSIVE EXCLUSIONS

"""
ENHANCED PROGRAM OVERVIEW: NHL Forward Points Per Game Prediction with Team Context + Experience Features
=======================================================================================================

This enhanced program builds machine learning models to predict NHL forward points per game using 
historical (lagged) performance data including individual stats, team context, player experience, 
and non-linear interactions. Version 6.0 introduces major improvements including target variable 
change to points per game, experience-based features, COVID season controls, and polynomial/interaction terms.

CRITICAL FIX: COMPREHENSIVE DATA LEAKAGE PREVENTION
==================================================
This version includes enhanced exclusion logic to prevent ALL contemporaneous variables from 
leaking into the model. Only properly lagged variables, engineered features from lagged data,
and control variables (COVID, interactions) are used for predictions.

MAJOR CHANGES IN VERSION 6.0:
============================
1. **TARGET VARIABLE CHANGE**: Now predicts POINTS PER GAME instead of total points
2. **TEAM DATA RESTRUCTURE**: Handles new single team structure (wins to face_off_win_pct_team)
3. **EXPERIENCE FEATURES**: Calculates and uses years played with interaction terms
4. **COVID CONTROLS**: Special handling for 2019-2020 and 2020-2021 seasons
5. **NON-LINEAR FEATURES**: Polynomial terms and interaction effects
6. **DUAL PREDICTIONS**: Outputs both actual games and 82-game projections
7. **ENHANCED RANKINGS**: Top 50 players by total points (not points per game)
8. **DATA LEAKAGE FIX**: Comprehensive exclusion of ALL current season variables

EXPECTED FOLDER STRUCTURE:
=========================
project_folder/
├── forward_points_model_v6.py (this script)
├── data_output/                  (input data folder)
│   ├── skater_team_data.csv     (merged player-team data - PRIMARY INPUT)
│   └── goalie_team_data.csv     (merged goalie-team data - optional)
├── nhl_plots/                   (output plots - created automatically)
└── nhl_results/                 (output results - created automatically)

REQUIRED INPUT FILE:
===================
- Primary: data_output/skater_team_data.csv (merged NHL player and team statistics)
- This file should contain player statistics merged with team information
- Team statistics now run from "wins" to "face_off_win_pct_team" columns
- Generated by the NHL data merger script from the NHL API data

NEW DATA STRUCTURE EXPECTATIONS:
===============================
- Team ID column: "team_id"
- Team statistics: "wins" through "face_off_win_pct_team"
- Player points: "points_player" or calculated from "goals" + "assists"
- Games played: "games_played"
- No more team1, team2, team3 numbered statistics

WORKFLOW STEP-BY-STEP:
=====================

1. DATA LOADING & CLEANING:
   - Loads NHL skater data from data_output/skater_team_data.csv
   - Removes all defensemen (keeps only forwards: C, LW, RW)
   - **NEW**: Calculates points per game as target variable
   - **NEW**: Identifies COVID seasons (2019-2020, 2020-2021) for special handling
   - **NEW**: Calculates years played for each player based on first/current season
   - Parses seasons and extracts year information
   - Handles missing data in core statistics
   - Preserves all legitimate performance data (no outlier capping)

2. **NEW**: EXPERIENCE AND TEMPORAL FEATURE CREATION:
   - Calculates years played for each player (career length measure)
   - Creates COVID season indicator variables
   - Develops polynomial terms (years_played^2, years_played^3)
   - Engineers interaction terms between years played and key stats

3. LAG FEATURE CREATION WITH UPDATED TEAM CONTEXT:
   - Creates 1, 2, or 3-year historical lags for key statistics
   - **UPDATED**: Team features now identified from "wins" to "face_off_win_pct_team"
   - Individual stats: goals, assists, shots, games_played, shooting_pct, time_on_ice_per_game
   - Power play stats: pp_goals, pp_assists, pp_shots, etc.
   - **NEW**: Team statistics from restructured single-team format
   - Filters data to years where complete lag history is available

4. ENHANCED FEATURE ENGINEERING WITH TEAM CONTEXT + EXPERIENCE:
   - Creates advanced metrics from lagged data including team context
   - **NEW**: Experience-based feature engineering (career progression metrics)
   - **NEW**: Non-linear transformations and polynomial features
   - **NEW**: Interaction effects between experience and performance
   - Historical averages, trends, momentum indicators
   - Team context metrics from lagged team statistics
   - Consistency measures and career trajectory features

5. FEATURE PREPARATION WITH COMPREHENSIVE EXCLUSIONS:
   - **CRITICAL**: Excludes ALL contemporaneous variables (no data leakage)
   - **NEW**: Includes COVID season controls as features
   - **NEW**: Includes experience features and interaction terms
   - Includes all historical individual, power play, and team statistics
   - Automatic feature selection with enhanced regularization
   - Handles new team structure and experience variables

6. REGULARIZATION WITH EXPERIENCE FEATURES:
   - Enhanced regularization for increased feature complexity
   - L1/L2 regularization for linear models
   - Tree-based regularization for ensemble methods
   - **NEW**: Additional regularization for polynomial and interaction terms
   - Cross-validation with time-aware splits

7. **UPDATED**: TWO ENHANCED TRAINING SCENARIOS FOR POINTS PER GAME:
   - Training A: All data for points per game model development
   - Training B: Exclude 2024-2025, predict and validate points per game
   - **NEW**: Convert predictions to total points for ranking purposes

8. **NEW**: DUAL PREDICTION OUTPUT:
   - Predicts points per game for 2024-2025 season
   - Converts to total points using (a) actual games played and (b) 82 games
   - Ranks top 50 players by total points (not points per game)
   - Provides both scenarios for comprehensive analysis

KEY ENHANCED FEATURES (v6.0):
============================
- **POINTS PER GAME TARGET**: More meaningful per-game performance prediction
- **EXPERIENCE MODELING**: Years played with non-linear effects and interactions
- **COVID CONTROLS**: Special handling for pandemic-affected seasons
- **POLYNOMIAL FEATURES**: Non-linear transformations for key variables
- **INTERACTION TERMS**: Experience × performance cross-effects
- **UPDATED TEAM CONTEXT**: New single-team structure support
- **DUAL PROJECTIONS**: Both actual games and full season (82 games) predictions
- **ENHANCED RANKINGS**: Total points rankings for practical use
- **CAREER TRAJECTORY**: Models player development and aging curves
- **TEMPORAL CONTROLS**: Accounts for league-wide effects and anomalous seasons
- **NO DATA LEAKAGE**: Uses only historical data for predictions
- **COMPREHENSIVE REGULARIZATION**: Prevents overfitting with expanded feature set
- **PORTABLE**: Dynamic paths relative to current working directory

NEW FEATURES IN VERSION 6.0:
============================

1. **TARGET VARIABLE TRANSFORMATION**:
   - Points per game = (goals + assists) / games_played
   - More stable metric across different season lengths
   - Better handles injury-shortened seasons and COVID impacts

2. **PLAYER EXPERIENCE FEATURES**:
   - years_played: Career length based on first season vs current season
   - years_played_squared: Quadratic age/experience effects
   - years_played_cubed: Cubic effects for aging curves
   - experience × stats interactions: Allow performance to vary by career stage

3. **COVID SEASON CONTROLS**:
   - covid_2019_2020: Binary indicator for 2019-2020 season
   - covid_2020_2021: Binary indicator for 2020-2021 season
   - Accounts for shortened seasons, different playing conditions

4. **NON-LINEAR TRANSFORMATIONS**:
   - Polynomial terms for key continuous variables
   - Interaction effects between experience and performance metrics
   - Captures aging curves and career development patterns

5. **ENHANCED TEAM CONTEXT**:
   - Updated to handle single team structure
   - Team stats from "wins" to "face_off_win_pct_team"
   - Historical team performance with experience interactions

6. **DUAL PREDICTION FRAMEWORK**:
   - Primary: Points per game prediction
   - Secondary: Total points conversion for ranking
   - Both actual games and 82-game projections

TECHNICAL APPROACH UPDATES:
==========================
- Maintains all regularization techniques from v5.3
- Enhanced feature engineering for experience and non-linearities
- Updated team feature identification for new data structure
- COVID season handling with domain expertise
- Polynomial regularization to prevent overfitting
- Interaction term selection and regularization
- Career trajectory modeling with experience variables

OUTPUT UPDATES:
==============
1. **Points per game model performance** (primary metric)
2. **Total points rankings** for practical application
3. **Dual projections** (actual games vs 82 games)
4. **Experience feature importance** analysis
5. **COVID season impact** assessment
6. **Career stage interaction** effects
7. **Enhanced diagnostic plots** with new features
8. **Top 50 player rankings** by total projected points

This version provides more sophisticated modeling while maintaining the robust
foundation of v5.3, adding practical experience-based features and addressing
real-world hockey analytics needs.
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV, TimeSeriesSplit
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.feature_selection import SelectKBest, f_regression, RFECV
from sklearn.preprocessing import StandardScaler, RobustScaler, PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.pipeline import Pipeline
import matplotlib.pyplot as plt
import seaborn as sns
from typing import Tuple, Dict, Any, List
import warnings
import os
import sys
from datetime import datetime
warnings.filterwarnings('ignore')

class OutputManager:
    """Manages output to both console and file"""
    def __init__(self, output_file=None):
        self.terminal = sys.stdout
        self.log_file = None
        if output_file:
            os.makedirs(os.path.dirname(output_file), exist_ok=True)
            self.log_file = open(output_file, 'w')
    
    def write(self, message):
        self.terminal.write(message)
        if self.log_file:
            self.log_file.write(message)
    
    def flush(self):
        self.terminal.flush()
        if self.log_file:
            self.log_file.flush()
    
    def close(self):
        if self.log_file:
            self.log_file.close()

def find_csv_file() -> str:
    """
    Find the CSV data file in the data_output folder or other common locations.
    
    Expected primary location: data_output/skater_team_data.csv
    This file should be the merged player-team data from the NHL data merger script
    with the new single-team structure.
    
    Returns:
        Path to the CSV file if found
        
    Raises:
        FileNotFoundError: If CSV file cannot be found in any location
    """
    current_dir = os.getcwd()
    print(f"Current working directory: {current_dir}")
    
    # Primary file names to search for (in priority order)
    possible_filenames = [
        'skater_team_data.csv',     # Primary: merged player-team data
        'nhl_skater_data.csv', 
        'skater_data.csv',
        'hockey_data.csv',
        'nhl_data.csv'
    ]
    
    # Directory patterns to search in (in priority order)
    search_patterns = [
        'data_output',              # PRIMARY: expected location for merged data
        '',                         # Current directory
        'nhl_output',              # Legacy location
        'data',                    # Alternative data folder
        'hockeyanalytics/nhl_output',  # Legacy nested structure
        'Dropbox/hockeyanalytics/nhl_output',
        'Documents',
        'Desktop',
        'Downloads'
    ]
    
    print("\nSearching for CSV file (prioritizing data_output folder)...")
    
    for filename in possible_filenames:
        for pattern in search_patterns:
            if pattern:
                search_path = os.path.join(current_dir, pattern, filename)
            else:
                search_path = os.path.join(current_dir, filename)
            
            print(f"  Checking: {search_path}")
            if os.path.exists(search_path):
                print(f"Found CSV file: {search_path}")
                return search_path
    
    # If not found, provide helpful error message
    print("\nCSV file not found in expected locations.")
    print("\nExpected folder structure for v6.0:")
    print(f"  {current_dir}/")
    print(f"  ├── forward_points_model_v6.0.py (this script)")
    print(f"  ├── data_output/")
    print(f"  │   ├── skater_team_data.csv (PRIMARY INPUT - merged player-team data)")
    print(f"  │   └── goalie_team_data.csv (optional)")
    print(f"  ├── nhl_plots/ (created automatically)")
    print(f"  └── nhl_results/ (created automatically)")
    
    print(f"\nPlease ensure your merged player-team data file is located at:")
    print(f"  {os.path.join(current_dir, 'data_output', 'skater_team_data.csv')}")
    
    # Ask user for file path
    user_path = input("\nEnter the full path to your CSV file (or press Enter to exit): ").strip()
    if user_path and os.path.exists(user_path):
        return user_path
    elif user_path:
        raise FileNotFoundError(f"File not found: {user_path}")
    else:
        raise FileNotFoundError("No CSV file specified")

def setup_output_directories() -> Tuple[str, str]:
    """
    Create output directories relative to current working directory.
    
    Returns:
        Tuple of (plots_dir, results_dir) paths
    """
    current_dir = os.getcwd()
    
    # Create output directories relative to current directory
    plots_dir = os.path.join(current_dir, 'nhl_plots')
    results_dir = os.path.join(current_dir, 'nhl_results')
    
    os.makedirs(plots_dir, exist_ok=True)
    os.makedirs(results_dir, exist_ok=True)
    
    print(f"Output directories created:")
    print(f"  Plots: {plots_dir}")
    print(f"  Results: {results_dir}")
    
    return plots_dir, results_dir

class EnhancedHockeyPointsPerGamePredictor:
    """
    Enhanced NHL Forward Points Per Game Predictor v6.0
    
    Major enhancements in v6.0:
    - Predicts points per game instead of total points
    - Includes player experience features and non-linear terms
    - COVID season controls for 2019-2020 and 2020-2021
    - Updated team structure handling
    - Polynomial features and interaction terms
    - Dual prediction output (actual games vs 82 games)
    """
    
    def __init__(self, lag_years: int = 2, min_training_year: int = None, use_feature_selection: bool = True):
        """
        Initialize the enhanced predictor with experience and non-linear features.
        
        Args:
            lag_years: Number of years of historical data to use (1, 2, or 3)
            min_training_year: Minimum year to include in training (auto-calculated if None)
            use_feature_selection: Whether to apply automatic feature selection
        """
        self.scaler = RobustScaler()  # Robust to outliers
        self.model = None
        self.feature_selector = None
        self.feature_columns = None
        self.selected_features = None
        self.target_column = 'points_per_game'  # NEW: Changed from 'points' to 'points_per_game'
        self.lag_years = lag_years
        self.min_training_year = min_training_year
        self.use_feature_selection = use_feature_selection
        self.best_params = None
        
    def load_data(self, csv_path: str) -> pd.DataFrame:
        """
        Load hockey player statistics and create enhanced features including experience.
        
        NEW v6.0 Features:
        - Calculates points per game as target variable
        - Identifies and marks COVID seasons (2019-2020, 2020-2021)
        - Calculates years played for each player (experience feature)
        - Handles new team structure (wins to face_off_win_pct_team)
        
        Args:
            csv_path: Path to the merged player-team CSV file
            
        Returns:
            Enhanced DataFrame with experience features and COVID controls
        """
        df = pd.read_csv(csv_path)
        
        print(f"Original data shape: {df.shape}")
        print(f"Loaded merged player-team data from: {csv_path}")
        
        # Remove defensemen - check multiple possible position column names
        position_cols = ['position', 'pos', 'Position', 'Pos']
        position_col = None
        
        for col in position_cols:
            if col in df.columns:
                position_col = col
                break
        
        if position_col:
            original_count = len(df)
            df = df[~df[position_col].astype(str).str.upper().str.contains('D', na=False)]
            removed_count = original_count - len(df)
            print(f"Removed {removed_count} defensemen ({removed_count/original_count*100:.1f}%)")
            print(f"Remaining positions: {df[position_col].value_counts().to_dict()}")
        else:
            print("Warning: No position column found - cannot remove defensemen")
            print(f"Available columns: {list(df.columns)}")
        
        # Parse season to extract start year
        df['season_str'] = df['season'].astype(str)
        df['year'] = df['season_str'].str[:4].astype(int)
        
        print(f"Year range: {df['year'].min()} - {df['year'].max()}")
        print(f"Years in dataset: {sorted(df['year'].unique())}")
        
        # NEW v6.0: Calculate points per game as target variable
        df = self._create_points_per_game_target(df)
        
        # NEW v6.0: Create COVID season indicators
        df = self._create_covid_season_indicators(df)
        
        # NEW v6.0: Calculate years played for each player
        df = self._calculate_years_played(df)
        
        # Automatically set min_training_year if not specified
        if self.min_training_year is None:
            self.min_training_year = df['year'].min() + self.lag_years
            print(f"Auto-setting min_training_year to {self.min_training_year} (allows {self.lag_years}-year lags)")
        
        # Clean missing data issues
        df = self._clean_missing_data(df)
        
        # Sort by player and year for lag feature creation
        df = df.sort_values(['player_id', 'year'])
        
        # Show data availability by year
        year_counts = df['year'].value_counts().sort_index()
        print(f"\nObservations per year (forwards only):")
        for year, count in year_counts.items():
            covid_indicator = " (COVID)" if year in [2019, 2020] else ""
            print(f"  {year}: {count} player-seasons{covid_indicator}")
        
        return df
    
    def _create_points_per_game_target(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        NEW v6.0: Create points per game target variable.
        
        This is a more stable target than total points as it accounts for:
        - Injury-shortened seasons
        - COVID-affected seasons with different game counts
        - Trade scenarios where players play partial seasons
        
        Args:
            df: DataFrame with player statistics
            
        Returns:
            DataFrame with points_per_game target variable
        """
        print("\nCreating points per game target variable...")
        
        # Use points_player if available, otherwise calculate from goals + assists
        if 'points_player' in df.columns:
            df['total_points'] = df['points_player'].fillna(0)
            print("Using 'points_player' column for points calculation")
        elif 'goals' in df.columns and 'assists' in df.columns:
            df['total_points'] = df['goals'].fillna(0) + df['assists'].fillna(0)
            print("Calculating points from goals + assists")
        else:
            raise ValueError("Cannot find points_player column or goals+assists columns")
        
        # Handle games played column variations
        games_played_cols = ['games_played_player', 'games_played', 'gamesPlayed', 'GP', 'Games', 'games', 'Games_Played', 'gp']
        games_played_col = None
        
        for col in games_played_cols:
            if col in df.columns:
                games_played_col = col
                break
        
        if games_played_col:
            df['games_played'] = df[games_played_col].fillna(0).clip(lower=0)
            if games_played_col != 'games_played':
                print(f"Using '{games_played_col}' column for games played")
        else:
            raise ValueError(f"Cannot find games played column. Available columns: {list(df.columns)}")
        
        # Calculate points per game, handling division by zero
        
        # Only calculate points per game for players with games played > 0
        valid_games_mask = df['games_played'] > 0
        df.loc[valid_games_mask, 'points_per_game'] = (
            df.loc[valid_games_mask, 'total_points'] / df.loc[valid_games_mask, 'games_played']
        )
        
        # For players with 0 games, set points per game to 0
        df.loc[~valid_games_mask, 'points_per_game'] = 0
        
        # Basic statistics for points per game
        ppg_stats = df[df['points_per_game'] > 0]['points_per_game'].describe()
        print(f"Points per game statistics:")
        print(f"  Mean: {ppg_stats['mean']:.3f}")
        print(f"  Median: {ppg_stats['50%']:.3f}")
        print(f"  Max: {ppg_stats['max']:.3f}")
        print(f"  Players with >0 PPG: {len(df[df['points_per_game'] > 0])}")
        
        return df
    
    def _create_covid_season_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        NEW v6.0: Create indicator variables for COVID-affected seasons.
        
        The 2019-2020 and 2020-2021 seasons were significantly affected by COVID:
        - 2019-2020: Season suspended in March, shortened season
        - 2020-2021: Shortened season, different divisions, no fans
        
        Args:
            df: DataFrame with year information
            
        Returns:
            DataFrame with COVID season indicators
        """
        print("\nCreating COVID season indicators...")
        
        # Create COVID season indicators
        df['covid_2019_2020'] = (df['year'] == 2019).astype(int)
        df['covid_2020_2021'] = (df['year'] == 2020).astype(int)
        df['covid_season'] = ((df['year'] == 2019) | (df['year'] == 2020)).astype(int)
        
        covid_2019_count = df['covid_2019_2020'].sum()
        covid_2020_count = df['covid_2020_2021'].sum()
        total_covid = df['covid_season'].sum()
        
        print(f"COVID season indicators created:")
        print(f"  2019-2020 season observations: {covid_2019_count}")
        print(f"  2020-2021 season observations: {covid_2020_count}")
        print(f"  Total COVID-affected observations: {total_covid}")
        
        return df
    
    def _calculate_years_played(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        NEW v6.0: Calculate years played (career experience) for each player.
        
        Years played = Current season year - First season year + 1
        This creates an experience feature that can capture:
        - Rookie effects (years_played = 1)
        - Prime years (years_played = 3-10)
        - Veteran effects (years_played > 10)
        - Aging curves and career trajectories
        
        Args:
            df: DataFrame with player seasons
            
        Returns:
            DataFrame with years_played and related experience features
        """
        print("\nCalculating years played (experience features)...")
        
        # Calculate first season for each player
        first_seasons = df.groupby('player_id')['year'].min().reset_index()
        first_seasons.rename(columns={'year': 'first_season_year'}, inplace=True)
        
        # Merge back to main dataframe
        df = df.merge(first_seasons, on='player_id', how='left')
        
        # Calculate years played (career length at each observation)
        df['years_played'] = df['year'] - df['first_season_year'] + 1
        
        # Ensure years played is at least 1 and reasonable
        df['years_played'] = df['years_played'].clip(lower=1, upper=25)
        
        # NEW v6.0: Create polynomial terms for non-linear career effects
        df['years_played_squared'] = df['years_played'] ** 2
        df['years_played_cubed'] = df['years_played'] ** 3
        
        # Career stage indicators
        df['rookie_year'] = (df['years_played'] == 1).astype(int)
        df['prime_years'] = ((df['years_played'] >= 3) & (df['years_played'] <= 10)).astype(int)
        df['veteran_years'] = (df['years_played'] > 10).astype(int)
        
        # Experience statistics
        exp_stats = df['years_played'].describe()
        print(f"Years played statistics:")
        print(f"  Mean: {exp_stats['mean']:.1f} years")
        print(f"  Median: {exp_stats['50%']:.1f} years")
        print(f"  Max: {exp_stats['max']:.0f} years")
        print(f"  Rookies (1 year): {df['rookie_year'].sum()} observations")
        print(f"  Prime years (3-10): {df['prime_years'].sum()} observations")
        print(f"  Veterans (>10 years): {df['veteran_years'].sum()} observations")
        
        return df
    
    def _clean_missing_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Clean and handle missing data with enhanced domain knowledge for v6.0.
        
        Args:
            df: Raw DataFrame with potential missing data issues
            
        Returns:
            Cleaned DataFrame with missing data handled appropriately
        """
        print("\nCleaning missing data...")
        
        # Handle shooting percentage variations
        shooting_cols = ['shooting_pct', 'shooting_percentage', 'sh_pct', 'shootingPct']
        shooting_col = None
        for col in shooting_cols:
            if col in df.columns:
                shooting_col = col
                break
        
        if shooting_col:
            # Convert percentage to decimal if needed
            if df[shooting_col].max() > 1:
                df['shooting_pct'] = df[shooting_col] / 100
            else:
                df['shooting_pct'] = df[shooting_col]
        else:
            # Calculate shooting percentage from goals and shots if available
            goals_cols = ['goals', 'Goals', 'G']
            shots_cols = ['shots', 'Shots', 'S']
            
            goals_col = None
            shots_col = None
            
            for col in goals_cols:
                if col in df.columns:
                    goals_col = col
                    break
            for col in shots_cols:
                if col in df.columns:
                    shots_col = col
                    break
            
            if goals_col and shots_col:
                df['shooting_pct'] = df[goals_col] / df[shots_col].replace(0, np.nan)
                df['shooting_pct'] = df['shooting_pct'].fillna(0.1)  # League average fallback
                # Ensure we have standardized column names
                if goals_col != 'goals':
                    df['goals'] = df[goals_col]
                if shots_col != 'shots':
                    df['shots'] = df[shots_col]
            else:
                df['shooting_pct'] = 0.1  # League average fallback
        
        # Handle time_on_ice_per_game variations
        toi_cols = ['time_on_ice_per_game', 'toi_per_game', 'avg_toi', 'time_on_ice', 'timeOnIcePerGame', 'TOI', 'avgTOI']
        toi_col = None
        for col in toi_cols:
            if col in df.columns:
                toi_col = col
                break
        
        if toi_col and toi_col != 'time_on_ice_per_game':
            df['time_on_ice_per_game'] = df[toi_col]
        elif not toi_col:
            df['time_on_ice_per_game'] = 15.0  # Reasonable default for forwards
        
        # Handle assists column variations
        assists_cols = ['assists', 'Assists', 'A']
        assists_col = None
        for col in assists_cols:
            if col in df.columns:
                assists_col = col
                break
        if assists_col and assists_col != 'assists':
            df['assists'] = df[assists_col]
        
        # Clean up core statistical columns
        core_stats = ['goals', 'assists', 'shots', 'games_played', 'total_points']
        for stat in core_stats:
            if stat in df.columns:
                df[stat] = df[stat].fillna(0)
                df[stat] = df[stat].clip(lower=0)
        
        # Remove rows where essential data is completely missing
        essential_cols = ['player_id', 'year', 'games_played']
        before_essential = len(df)
        df = df.dropna(subset=essential_cols)
        after_essential = len(df)
        
        if before_essential != after_essential:
            print(f"Removed {before_essential - after_essential} rows missing essential data")
        
        # Remove players with 0 games played (clear data quality issue)
        if 'games_played' in df.columns:
            before_games = len(df)
            df = df[df['games_played'] > 0]
            after_games = len(df)
            if before_games != after_games:
                print(f"Removed {before_games - after_games} rows with 0 games played")
        
        print(f"Data shape after cleaning: {df.shape}")
        return df
    
    def create_lag_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Create lagged features including updated team structure and experience interactions.
        
        NEW v6.0 Updates:
        - Updated team feature identification for new structure (wins to face_off_win_pct_team)
        - Includes experience features in lag creation
        - Creates interaction terms between lagged stats and experience
        
        Args:
            df: DataFrame with enhanced features including experience
            
        Returns:
            DataFrame with comprehensive lag features
        """
        # Individual stats for lagging
        individual_features = ['goals', 'assists', 'shots', 'games_played', 'shooting_pct', 
                             'time_on_ice_per_game', 'points_per_game', 'total_points']
        
        # Power play features
        pp_features = [col for col in df.columns if col.startswith('pp') and 'lag' not in col]
        
        # NEW v6.0: Updated team feature identification
        # Look for team features from "wins" to "face_off_win_pct_team"
        team_features = self._identify_team_features(df)
        
        # Experience features to lag
        experience_features = ['years_played', 'years_played_squared', 'years_played_cubed']
        
        # Combine all features for lagging
        all_lag_features = individual_features + pp_features + team_features + experience_features
        existing_features = [f for f in all_lag_features if f in df.columns]
        
        print(f"\nCreating {self.lag_years}-year lags for {len(existing_features)} features:")
        print(f"  Individual stats: {len([f for f in existing_features if f in individual_features])}")
        print(f"  Power play stats: {len([f for f in existing_features if f in pp_features])}")
        print(f"  Team statistics: {len([f for f in existing_features if f in team_features])}")
        print(f"  Experience features: {len([f for f in existing_features if f in experience_features])}")
        
        df_with_lags = df.copy()
        
        # Initialize lag columns
        lag_columns = []
        for feature in existing_features:
            for lag in range(1, self.lag_years + 1):
                lag_col = f'{feature}_lag{lag}'
                lag_columns.append(lag_col)
                df_with_lags[lag_col] = np.nan
        
        print(f"  Total lag columns created: {len(lag_columns)}")
        
        # Create lags for each player individually
        players_with_sufficient_history = 0
        
        for player in df['player_id'].unique():
            player_data = df[df['player_id'] == player].sort_values('year')
            
            if len(player_data) > self.lag_years:
                players_with_sufficient_history += 1
                
                for feature in existing_features:
                    for lag in range(1, self.lag_years + 1):
                        lag_col = f'{feature}_lag{lag}'
                        lagged_values = player_data[feature].shift(lag)
                        df_with_lags.loc[df_with_lags['player_id'] == player, lag_col] = lagged_values
        
        print(f"Players with sufficient history: {players_with_sufficient_history}")
        
        # Filter to training years
        training_data = df_with_lags[df_with_lags['year'] >= self.min_training_year].copy()
        print(f"Training data shape after year filter: {training_data.shape}")
        
        return training_data
    
    def _identify_team_features(self, df: pd.DataFrame) -> List[str]:
        """
        NEW v6.0: Identify team features based on new structure.
        
        Team features now run from "wins" to "face_off_win_pct_team" instead of 
        the old team1, team2, team3 numbering system.
        
        Args:
            df: DataFrame with team statistics
            
        Returns:
            List of team feature column names
        """
        team_features = []
        
        # Check if we have the expected team structure
        if 'wins' in df.columns and 'face_off_win_pct_team' in df.columns:
            # Get all columns between wins and face_off_win_pct_team
            cols = list(df.columns)
            try:
                start_idx = cols.index('wins')
                end_idx = cols.index('face_off_win_pct_team')
                team_features = cols[start_idx:end_idx+1]
                print(f"  Identified {len(team_features)} team features from 'wins' to 'face_off_win_pct_team'")
            except ValueError:
                print("  Warning: Could not find team feature range")
        
        # Fallback: look for any remaining team-like features
        if not team_features:
            # Look for columns that might be team stats
            possible_team_cols = [col for col in df.columns if any(indicator in col.lower() 
                                 for indicator in ['team', 'wins', 'losses', 'goals_for', 'goals_against'])]
            team_features.extend(possible_team_cols)
            
        # Remove any non-numeric columns
        numeric_team_features = []
        for col in team_features:
            if col in df.columns:
                try:
                    pd.to_numeric(df[col], errors='raise')
                    numeric_team_features.append(col)
                except:
                    continue
        
        print(f"  Final team features for lagging: {numeric_team_features[:10]}...")  # Show first 10
        return numeric_team_features
    
    def engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Enhanced feature engineering with experience interactions and non-linear terms.
        
        NEW v6.0 Features:
        - Interaction terms between experience and performance
        - Non-linear transformations of key variables
        - COVID season interaction effects
        - Enhanced career trajectory features
        
        Args:
            df: DataFrame with lag features
            
        Returns:
            DataFrame with comprehensive engineered features
        """
        print(f"\nEngineering enhanced features with experience and non-linear terms...")
        
        df_eng = df.copy()
        
        # Find all lag columns
        lag_columns = [col for col in df_eng.columns if 'lag' in col]
        
        if lag_columns:
            print(f"Found {len(lag_columns)} lag columns for feature engineering")
            
            # Get base features that have lags
            base_features = list(set([col.replace('_lag1', '').replace('_lag2', '').replace('_lag3', '') 
                                    for col in lag_columns]))
            
            print(f"Engineering features for {len(base_features)} base features")
            
            # Standard lag-based features (from v5.3)
            for base_feature in base_features:
                lag_cols = [col for col in lag_columns if col.startswith(f'{base_feature}_lag')]
                
                if lag_cols:
                    # Historical averages
                    df_eng[f'{base_feature}_hist_avg'] = df_eng[lag_cols].mean(axis=1, skipna=True)
                    
                    # Historical consistency (if multiple lags)
                    if len(lag_cols) >= 2:
                        df_eng[f'{base_feature}_hist_std'] = df_eng[lag_cols].std(axis=1, skipna=True).fillna(0)
                    
                    # Recent trends
                    if len(lag_cols) >= 2 and f'{base_feature}_lag1' in df_eng.columns and f'{base_feature}_lag2' in df_eng.columns:
                        trend = df_eng[f'{base_feature}_lag1'] - df_eng[f'{base_feature}_lag2']
                        df_eng[f'{base_feature}_trend'] = trend.fillna(0)
            
            # NEW v6.0: Experience interaction terms
            self._create_experience_interactions(df_eng, lag_columns)
            
            # NEW v6.0: COVID season interactions
            self._create_covid_interactions(df_eng, lag_columns)
            
            # NEW v6.0: Career trajectory features
            self._create_career_trajectory_features(df_eng)
        
        # Create per-game rates from historical data (focus on individual stats)
        for lag in range(1, min(self.lag_years + 1, 3)):
            if f'goals_lag{lag}' in df_eng.columns and f'games_played_lag{lag}' in df_eng.columns:
                goals_per_game = df_eng[f'goals_lag{lag}'] / df_eng[f'games_played_lag{lag}'].replace(0, np.nan)
                df_eng[f'goals_per_game_lag{lag}'] = goals_per_game.fillna(0)
                
            if f'assists_lag{lag}' in df_eng.columns and f'games_played_lag{lag}' in df_eng.columns:
                assists_per_game = df_eng[f'assists_lag{lag}'] / df_eng[f'games_played_lag{lag}'].replace(0, np.nan)
                df_eng[f'assists_per_game_lag{lag}'] = assists_per_game.fillna(0)
        
        # Clean up infinite and extreme values
        df_eng = df_eng.replace([np.inf, -np.inf], np.nan)
        
        # Fill remaining NaN values with appropriate defaults
        numeric_cols = df_eng.select_dtypes(include=[np.number]).columns
        df_eng[numeric_cols] = df_eng[numeric_cols].fillna(0)
        
        print(f"Final engineered data shape: {df_eng.shape}")
        
        return df_eng
    
    def _create_experience_interactions(self, df_eng: pd.DataFrame, lag_columns: List[str]) -> None:
        """
        NEW v6.0: Create interaction terms between experience and performance.
        
        These interactions allow performance metrics to have different effects
        based on player experience level (rookies vs veterans).
        
        Args:
            df_eng: DataFrame to add interaction terms to
            lag_columns: List of lag column names
        """
        print("  Creating experience interaction terms...")
        
        # Key performance metrics to interact with experience
        key_performance_lags = [col for col in lag_columns 
                               if any(metric in col for metric in ['goals_lag', 'assists_lag', 'points_per_game_lag', 'shots_lag'])]
        
        # Create interactions with years_played
        interaction_count = 0
        for perf_col in key_performance_lags[:15]:  # Limit to prevent feature explosion
            if perf_col in df_eng.columns and 'years_played' in df_eng.columns:
                interaction_name = f'{perf_col}_x_experience'
                df_eng[interaction_name] = df_eng[perf_col] * df_eng['years_played']
                interaction_count += 1
        
        print(f"    Created {interaction_count} experience interaction terms")
    
    def _create_covid_interactions(self, df_eng: pd.DataFrame, lag_columns: List[str]) -> None:
        """
        NEW v6.0: Create COVID season interaction effects.
        
        Allow performance metrics to have different effects during COVID seasons.
        
        Args:
            df_eng: DataFrame to add COVID interactions to
            lag_columns: List of lag column names
        """
        print("  Creating COVID season interaction terms...")
        
        # Key metrics that might be affected differently during COVID
        covid_metrics = [col for col in lag_columns 
                        if any(metric in col for metric in ['points_per_game_lag', 'goals_lag', 'assists_lag'])]
        
        covid_interaction_count = 0
        for metric in covid_metrics[:10]:  # Limit interactions
            if metric in df_eng.columns and 'covid_season' in df_eng.columns:
                interaction_name = f'{metric}_x_covid'
                df_eng[interaction_name] = df_eng[metric] * df_eng['covid_season']
                covid_interaction_count += 1
        
        print(f"    Created {covid_interaction_count} COVID interaction terms")
    
    def _create_career_trajectory_features(self, df_eng: pd.DataFrame) -> None:
        """
        NEW v6.0: Create career trajectory and aging curve features.
        
        Args:
            df_eng: DataFrame to add career features to
        """
        print("  Creating career trajectory features...")
        
        trajectory_features = 0
        
        # Career stage performance differentials
        if 'points_per_game_lag1' in df_eng.columns:
            # Performance in rookie year
            if 'rookie_year' in df_eng.columns:
                df_eng['rookie_performance'] = df_eng['points_per_game_lag1'] * df_eng['rookie_year']
                trajectory_features += 1
            
            # Prime years performance
            if 'prime_years' in df_eng.columns:
                df_eng['prime_performance'] = df_eng['points_per_game_lag1'] * df_eng['prime_years']
                trajectory_features += 1
        
        print(f"    Created {trajectory_features} career trajectory features")
    
    def prepare_features(self, df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.Series]:
        """
        Prepare feature matrix and target using enhanced feature set.
        
        NEW v6.0: 
        - Uses points_per_game as target
        - Includes experience features and interactions
        - Includes COVID controls
        - CRITICAL: Comprehensive exclusion of ALL current season variables
        
        Args:
            df: DataFrame with all engineered features
            
        Returns:
            Tuple of (feature matrix X, target vector y)
        """
        print(f"\nPreparing features for points per game prediction")
        print(f"Initial data shape: {len(df)} observations and {len(df.columns)} columns")
        
        # CRITICAL: Exclude ALL contemporaneous variables to prevent data leakage
        exclude_cols = [
            # Core identifiers
            'player_id', 'season', 'season_str', 'year', 'first_season_year',
            # Team identifiers and names
            'team_id', 'team_code', 'team_name', 'teamId', 'teamCode', 'teamName', 'team',
            # Target variables (current season)
            'points_per_game', 'total_points',
            # Basic current season stats
            'goals', 'assists', 'shots', 'games_played_player', 'games_played',
            'shooting_pct', 'time_on_ice_per_game', 'plus_minus', 'plusMinus',
            # Additional current season stats that could leak
            'gw_goals', 'ot_goals', 'penalty_minutes', 'pim', 'hits', 'blocked_shots',
            'takeaways', 'giveaways', 'faceoff_wins', 'faceoffs_taken', 'shifts',
            # Current season experience (use lagged instead)
            'years_played', 'years_played_squared', 'years_played_cubed', 
            'rookie_year', 'prime_years', 'veteran_years',
            # Position and demographic info
            'position', 'pos', 'Position', 'Pos', 'age', 'height', 'weight',
        ]
        
        # COMPREHENSIVE: Exclude ALL current season variables (anything without 'lag' in the name)
        print("  Identifying and excluding ALL current season variables...")
        current_season_excluded = 0
        
        for col in df.columns:
            # Skip if already in exclude list or is a lag variable
            if col in exclude_cols or 'lag' in col:
                continue
                
            # Exclude ALL remaining non-lag variables that could be current season stats
            if any(indicator in col.lower() for indicator in [
                'pp_', 'sh_', 'pk_', 'sv_', 'goals', 'assists', 'shots', 'points', 
                'plus_minus', 'pm_', 'penalty', 'pim', 'hits', 'blocks', 'takeaway',
                'giveaway', 'faceoff', 'shift', 'ice_time', 'toi', 'saves', 'wins',
                'losses', 'ties', 'otl', 'points_pct', 'gf_', 'ga_', 'diff',
                'streak', 'home_', 'away_', 'last_10', 'percent', 'rate', 'avg'
            ]):
                # Double-check it's not a lag variable or engineered feature we want to keep
                if ('lag' not in col and 'hist' not in col and 'trend' not in col and 
                    'covid' not in col and '_x_' not in col):
                    exclude_cols.append(col)
                    current_season_excluded += 1
        
        print(f"  Excluded {current_season_excluded} additional current season variables")
        
        # Exclude text and name columns
        name_indicators = ['name', 'player', 'firstname', 'lastname', 'full_name', 'player_name']
        for col in df.columns:
            col_lower = col.lower()
            if any(indicator in col_lower for indicator in name_indicators):
                exclude_cols.append(col)
        
        # Remove duplicates
        exclude_cols = list(set(exclude_cols))
        potential_features = [col for col in df.columns if col not in exclude_cols]
        
        print(f"Potential features after exclusions: {len(potential_features)}")
        
        # CRITICAL: Remove non-numeric columns that could cause sklearn errors
        numeric_features = []
        for col in potential_features:
            if col in df.columns:
                try:
                    # Test if column can be converted to numeric
                    pd.to_numeric(df[col], errors='raise')
                    numeric_features.append(col)
                except (ValueError, TypeError):
                    # Check if it's mostly numeric with some NaN
                    try:
                        pd.to_numeric(df[col], errors='coerce')
                        # If we get here, it's convertible with coercion, keep it
                        numeric_features.append(col)
                        print(f"  Converting '{col}' to numeric (had some non-numeric values)")
                    except:
                        print(f"  Excluding non-numeric column: '{col}' (sample values: {df[col].dropna().head(3).tolist()})")
        
        # Remove features with excessive missing data
        good_features = []
        for col in numeric_features:
            missing_pct = df[col].isnull().sum() / len(df) * 100
            if missing_pct <= 70:  # Slightly more strict for enhanced model
                good_features.append(col)
            else:
                print(f"Excluding '{col}' due to {missing_pct:.1f}% missing data")
        
        self.feature_columns = good_features
        print(f"Final feature count: {len(self.feature_columns)}")
        
        # Enhanced feature categorization for v6.0
        individual_features = [f for f in self.feature_columns if 'lag' in f and 
                             not f.startswith('pp') and not any(team_f in f for team_f in ['wins', 'losses'])]
        pp_features = [f for f in self.feature_columns if 'lag' in f and f.startswith('pp')]
        team_features = [f for f in self.feature_columns if 'lag' in f and 
                        any(team_f in f for team_f in ['wins', 'losses', 'goals_for', 'goals_against'])]
        experience_features = [f for f in self.feature_columns if 'years_played' in f or 'rookie' in f or 'prime' in f or 'veteran' in f]
        covid_features = [f for f in self.feature_columns if 'covid' in f]
        interaction_features = [f for f in self.feature_columns if '_x_' in f]
        engineered_features = [f for f in self.feature_columns if 'hist' in f or 'trend' in f]
        
        print(f"\nENHANCED FEATURE BREAKDOWN (v6.0 - DATA LEAKAGE FIXED):")
        print("-" * 65)
        print(f"Individual lagged features: {len(individual_features)}")
        print(f"Power play lagged features: {len(pp_features)}")
        print(f"Team lagged features: {len(team_features)}")
        print(f"Experience features: {len(experience_features)}")
        print(f"COVID control features: {len(covid_features)}")
        print(f"Interaction features: {len(interaction_features)}")
        print(f"Engineered features: {len(engineered_features)}")
        
        # Get feature matrix and target
        X = df[self.feature_columns].copy()
        y = df[self.target_column].copy()
        
        print(f"\nBefore missing data removal: {len(X)} observations")
        
        # CRITICAL: Force conversion of all features to numeric and identify problematic columns
        print("Converting all features to numeric and identifying problematic data...")
        problematic_cols = []
        for col in X.columns:
            # Check for string values first
            string_mask = X[col].astype(str).str.contains('[A-Za-z]', na=False, regex=True)
            if string_mask.any():
                string_values = X.loc[string_mask, col].unique()[:5]  # Get first 5 string values
                problematic_cols.append((col, string_values))
                print(f"  WARNING: Column '{col}' contains strings: {string_values}")
                
                # Force conversion to numeric (strings become NaN)
                X[col] = pd.to_numeric(X[col], errors='coerce')
        
        if problematic_cols:
            print(f"  Converted {len(problematic_cols)} columns with string data to numeric (strings → NaN)")
        
        # Additional safety check: verify all data is numeric
        print("Final verification that all data is numeric...")
        for col in X.columns:
            if X[col].dtype == 'object' or X[col].dtype.name == 'string':
                print(f"  REMOVING: Column '{col}' still has object/string dtype")
                X = X.drop(columns=[col])
                self.feature_columns.remove(col)
        
        print(f"Final feature matrix shape after data cleaning: {X.shape}")
        
        # Handle missing data
        core_features = [f for f in X.columns if any(core in f for core in ['goals_lag', 'assists_lag', 'games_played'])]
        
        if core_features:
            missing_mask = X[core_features].isnull().all(axis=1) | y.isnull()
        else:
            missing_mask = X.isnull().all(axis=1) | y.isnull()
        
        if missing_mask.any():
            X_clean = X[~missing_mask]
            y_clean = y[~missing_mask]
            print(f"Removed {missing_mask.sum()} rows with missing core data")
        else:
            X_clean = X
            y_clean = y
        
        # Fill remaining missing values
        X_clean = X_clean.fillna(0)
        
        print(f"After missing data handling: {len(X_clean)} observations")
        print(f"Final feature matrix shape: {X_clean.shape}")
        
        return X_clean, y_clean
    
    def train_model_with_enhanced_regularization(self, X: pd.DataFrame, y: pd.Series, model_type: str = 'random_forest') -> Dict[str, Any]:
        """
        Train model with enhanced regularization for expanded feature set.
        
        NEW v6.0: Enhanced regularization to handle increased complexity from
        experience features, interactions, and polynomial terms.
        
        Args:
            X: Feature matrix with enhanced features
            y: Target variable (points per game)
            model_type: Type of model to train
            
        Returns:
            Dictionary containing training results and metrics
        """
        print(f"\nTraining {model_type} with enhanced regularization (v6.0):")
        print(f"  Training data shape: {X.shape}")
        print(f"  Target: {self.target_column}")
        
        if len(X) < 20:
            raise ValueError(f"Insufficient data for training: {len(X)} observations")
        
        # Enhanced feature selection for expanded feature set
        if self.use_feature_selection and len(self.feature_columns) > 20:
            print(f"  Applying enhanced feature selection...")
            # More conservative feature selection for polynomial/interaction terms
            k_features = min(50, max(15, len(self.feature_columns) // 3))  # More features allowed
            self.feature_selector = SelectKBest(score_func=f_regression, k=k_features)
            X_selected = self.feature_selector.fit_transform(X, y)
            self.selected_features = X.columns[self.feature_selector.get_support()].tolist()
            print(f"  Selected {len(self.selected_features)} features from {len(self.feature_columns)}")
            X = pd.DataFrame(X_selected, columns=self.selected_features, index=X.index)
        else:
            self.selected_features = self.feature_columns
        
        # Split data
        test_size = min(0.25, max(0.15, 40/len(X)))
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)
        
        print(f"  Train size: {len(X_train)}")
        print(f"  Test size: {len(X_test)}")
        
        # Enhanced model configurations for v6.0
        models = self._get_enhanced_models_v6()
        
        if model_type not in models:
            raise ValueError(f"Unknown model type: {model_type}")
        
        model_config = models[model_type]
        
        # Scale features for linear models (important for polynomial terms)
        if model_type in ['ridge', 'lasso', 'elastic_net']:
            X_train_scaled = self.scaler.fit_transform(X_train)
            X_test_scaled = self.scaler.transform(X_test)
            X_train_final = X_train_scaled
            X_test_final = X_test_scaled
        else:
            X_train_final = X_train
            X_test_final = X_test
        
        # Enhanced hyperparameter tuning
        print(f"  Performing enhanced hyperparameter tuning...")
        cv_folds = min(5, max(3, len(X_train) // 30))
        
        if model_config['search_type'] == 'randomized':
            search = RandomizedSearchCV(
                estimator=model_config['model'],
                param_distributions=model_config['params'],
                n_iter=model_config['n_iter'],
                cv=cv_folds,
                scoring='r2',
                n_jobs=-1,
                random_state=42,
                return_train_score=True
            )
        else:
            search = GridSearchCV(
                estimator=model_config['model'],
                param_grid=model_config['params'],
                cv=cv_folds,
                scoring='r2',
                n_jobs=-1,
                return_train_score=True
            )
        
        search.fit(X_train_final, y_train)
        
        self.model = search.best_estimator_
        self.best_params = search.best_params_
        
        print(f"  Best parameters: {self.best_params}")
        print(f"  Best CV score: {search.best_score_:.3f}")
        
        # Predictions and metrics
        y_pred = self.model.predict(X_test_final)
        
        mae = mean_absolute_error(y_test, y_pred)
        mse = mean_squared_error(y_test, y_pred)
        rmse = np.sqrt(mse)
        r2 = r2_score(y_test, y_pred)
        
        train_score = self.model.score(X_train_final, y_train)
        test_score = r2
        overfitting_ratio = (train_score - test_score) / train_score if train_score > 0 else 0
        
        results = {
            'mae': mae, 'mse': mse, 'rmse': rmse, 'r2': r2,
            'train_r2': train_score, 'test_r2': test_score,
            'overfitting_ratio': overfitting_ratio,
            'cv_mean': search.best_score_,
            'cv_std': search.cv_results_['std_test_score'][search.best_index_],
            'y_test': y_test, 'y_pred': y_pred,
            'model_type': model_type,
            'best_params': self.best_params,
            'n_train': len(X_train), 'n_test': len(X_test),
            'n_features_selected': len(self.selected_features)
        }
        
        print(f"  R² Score: {r2:.3f}")
        print(f"  RMSE: {rmse:.3f} points per game")
        print(f"  MAE: {mae:.3f} points per game")
        print(f"  Train R²: {train_score:.3f}")
        print(f"  Overfitting ratio: {overfitting_ratio:.3f}")
        
        return results
    
    def _get_enhanced_models_v6(self) -> Dict[str, Any]:
        """
        Enhanced model configurations for v6.0 with polynomial/interaction regularization.
        
        Returns:
            Dictionary of enhanced model configurations
        """
        models = {
            'random_forest': {
                'model': RandomForestRegressor(random_state=42, n_jobs=-1),
                'params': {
                    'n_estimators': [150, 250],          # Slightly more trees for complexity
                    'max_depth': [12, 18],               # Slightly deeper for interactions
                    'min_samples_split': [15, 25],       # More conservative to prevent overfitting
                    'min_samples_leaf': [8, 12],         # More conservative
                    'max_features': ['sqrt', 0.4]        # Less aggressive feature sampling
                },
                'search_type': 'randomized',
                'n_iter': 8
            },
            'gradient_boosting': {
                'model': GradientBoostingRegressor(random_state=42, validation_fraction=0.2, n_iter_no_change=10),
                'params': {
                    'n_estimators': [150, 250],
                    'max_depth': [4, 6],                 # Conservative depth for interactions
                    'learning_rate': [0.05, 0.1],       # Lower learning rate for stability
                    'subsample': [0.8, 0.9],
                    'min_samples_split': [15, 25],
                    'max_features': ['sqrt', 0.4]
                },
                'search_type': 'randomized',
                'n_iter': 10
            },
            'ridge': {
                'model': Ridge(random_state=42),
                'params': {
                    'alpha': [10.0, 50.0, 100.0, 500.0]  # Stronger regularization for polynomials
                },
                'search_type': 'grid'
            },
            'lasso': {
                'model': Lasso(random_state=42, max_iter=3000),
                'params': {
                    'alpha': [0.1, 0.5, 1.0, 5.0]       # Range suitable for feature selection
                },
                'search_type': 'grid'
            },
            'elastic_net': {
                'model': ElasticNet(random_state=42, max_iter=3000),
                'params': {
                    'alpha': [0.1, 1.0, 5.0],
                    'l1_ratio': [0.3, 0.5, 0.7]
                },
                'search_type': 'grid'
            }
        }
        return models
    
    def predict_season_with_dual_output(self, df_full: pd.DataFrame, target_year: int) -> pd.DataFrame:
        """
        NEW v6.0: Predict points per game and convert to total points rankings.
        
        Creates dual output:
        (a) Total points based on actual games played in target year
        (b) Total points projected to 82 games
        
        Args:
            df_full: Complete dataset including target year
            target_year: Year to predict (e.g., 2024 for 2024-2025 season)
            
        Returns:
            DataFrame with predictions and dual total points calculations
        """
        if self.model is None:
            raise ValueError("Model must be trained first")
            
        # Get target year data
        target_data = df_full[df_full['year'] == target_year].copy()
        
        if len(target_data) == 0:
            raise ValueError(f"No data found for year {target_year}")
        
        print(f"\nPredicting {target_year} season with dual output:")
        print(f"  Players to predict: {len(target_data)}")
        
        # Prepare features
        X_pred, _ = self.prepare_features(target_data)
        
        # Apply feature selection if used during training
        if self.feature_selector is not None:
            X_pred_selected = X_pred[self.selected_features]
        else:
            X_pred_selected = X_pred
        
        print(f"  Players with complete feature data: {len(X_pred_selected)}")
        
        # Scale features if linear model
        if hasattr(self.scaler, 'transform') and self.best_params and self.model.__class__.__name__ in ['Ridge', 'Lasso', 'ElasticNet']:
            X_pred_final = self.scaler.transform(X_pred_selected)
        else:
            X_pred_final = X_pred_selected
        
        # Make predictions (points per game)
        predicted_ppg = self.model.predict(X_pred_final)
        
        # Create results dataframe
        results_df = target_data.loc[X_pred_selected.index].copy()
        results_df['predicted_ppg'] = predicted_ppg
        
        # NEW v6.0: Convert to total points for ranking
        # (a) Actual games played
        results_df['actual_games'] = results_df['games_played'].fillna(0)
        results_df['predicted_points_actual'] = results_df['predicted_ppg'] * results_df['actual_games']
        
        # (b) Projected to 82 games
        results_df['predicted_points_82games'] = results_df['predicted_ppg'] * 82
        
        # Add actual total points for comparison
        if 'total_points' in results_df.columns:
            results_df['actual_total_points'] = results_df['total_points']
        elif 'points_player' in results_df.columns:
            results_df['actual_total_points'] = results_df['points_player']
        else:
            results_df['actual_total_points'] = results_df.get('goals', 0) + results_df.get('assists', 0)
        
        # Sort by predicted total points (82 games) for ranking
        results_df = results_df.sort_values('predicted_points_82games', ascending=False)
        
        # Return relevant columns
        return_cols = ['player_name', 'predicted_ppg', 'actual_games', 
                      'predicted_points_actual', 'predicted_points_82games', 'actual_total_points']
        
        return results_df[return_cols].reset_index(drop=True)
    
    def get_enhanced_feature_importance(self, top_n: int = 25) -> pd.DataFrame:
        """
        Enhanced feature importance analysis for v6.0.
        
        Args:
            top_n: Number of top features to return
            
        Returns:
            DataFrame with enhanced feature categorization
        """
        if self.model is None:
            raise ValueError("Model must be trained first")
        
        # Get importance values
        if hasattr(self.model, 'feature_importances_'):
            importance = self.model.feature_importances_
        else:
            importance = np.abs(self.model.coef_)
        
        feature_names = self.selected_features if self.selected_features else self.feature_columns
        
        importance_df = pd.DataFrame({
            'feature': feature_names,
            'importance': importance
        }).sort_values('importance', ascending=False)
        
        # Enhanced categorization for v6.0
        def categorize_feature_v6(feature_name):
            if 'covid' in feature_name.lower():
                return "COVID"
            elif 'years_played' in feature_name or 'rookie' in feature_name or 'prime' in feature_name or 'veteran' in feature_name:
                return "EXPERIENCE"
            elif '_x_' in feature_name:
                return "INTERACTION"
            elif any(team_indicator in feature_name.lower() for team_indicator in ['wins', 'losses', 'goals_for', 'goals_against']):
                return "TEAM"
            elif feature_name.startswith('pp'):
                return "POWERPLAY"
            else:
                return "INDIVIDUAL"
        
        importance_df['type'] = importance_df['feature'].apply(categorize_feature_v6)
        
        return importance_df.head(top_n)
    
    def plot_enhanced_results_v6(self, results: Dict[str, Any], save_path: str = None):
        """
        Enhanced plotting for v6.0 with points per game focus and new feature categories.
        
        Creates a comprehensive 6-panel plot showing:
        1. Actual vs Predicted PPG scatter plot
        2. Residual plot  
        3. Enhanced feature importance with v6.0 categories
        4. Residual distribution
        5. Train vs Test performance comparison
        6. Model configuration summary for v6.0
        
        Args:
            results: Dictionary containing model results and metrics
            save_path: Optional path to save the plot
        """
        fig, axes = plt.subplots(2, 3, figsize=(20, 12))
        
        # Panel 1: Actual vs Predicted Points Per Game
        axes[0, 0].scatter(results['y_test'], results['y_pred'], alpha=0.6, color='blue')
        min_val, max_val = results['y_test'].min(), results['y_test'].max()
        axes[0, 0].plot([min_val, max_val], [min_val, max_val], 'r--', lw=2)
        axes[0, 0].set_xlabel('Actual Points Per Game')
        axes[0, 0].set_ylabel('Predicted Points Per Game')
        axes[0, 0].set_title(f'Points Per Game Prediction (v6.0 Enhanced)\nR² = {results["r2"]:.3f}, Overfitting = {results["overfitting_ratio"]:.3f}')
        axes[0, 0].grid(True, alpha=0.3)
        
        # Panel 2: Residuals
        residuals = results['y_test'] - results['y_pred']
        axes[0, 1].scatter(results['y_pred'], residuals, alpha=0.6, color='green')
        axes[0, 1].axhline(y=0, color='r', linestyle='--')
        axes[0, 1].set_xlabel('Predicted Points Per Game')
        axes[0, 1].set_ylabel('Residuals')
        axes[0, 1].set_title('Residual Plot')
        axes[0, 1].grid(True, alpha=0.3)
        
        # Panel 3: Enhanced Feature Importance with v6.0 categories
        try:
            importance_df = self.get_enhanced_feature_importance(15)
            
            # Enhanced color scheme for v6.0 categories
            colors = {
                'INDIVIDUAL': 'blue', 
                'TEAM': 'red', 
                'POWERPLAY': 'green',
                'EXPERIENCE': 'orange',
                'INTERACTION': 'purple',
                'COVID': 'brown'
            }
            bar_colors = [colors.get(t, 'gray') for t in importance_df['type']]
            
            bars = axes[0, 2].barh(range(len(importance_df)), importance_df['importance'], 
                                  color=bar_colors, alpha=0.7)
            axes[0, 2].set_yticks(range(len(importance_df)))
            axes[0, 2].set_yticklabels([f.replace('_lag', '_l').replace('_hist_avg', '_avg')[:25] 
                                       for f in importance_df['feature']], fontsize=8)
            axes[0, 2].set_xlabel('Importance')
            axes[0, 2].set_title(f'Feature Importance (Top 15)\n{results["n_features_selected"]} features selected')
            
            # Enhanced legend for v6.0
            from matplotlib.patches import Patch
            legend_elements = [
                Patch(facecolor='blue', alpha=0.7, label='Individual'),
                Patch(facecolor='red', alpha=0.7, label='Team'),
                Patch(facecolor='green', alpha=0.7, label='PowerPlay'),
                Patch(facecolor='orange', alpha=0.7, label='Experience'),
                Patch(facecolor='purple', alpha=0.7, label='Interaction'),
                Patch(facecolor='brown', alpha=0.7, label='COVID')
            ]
            axes[0, 2].legend(handles=legend_elements, loc='lower right', fontsize=7)
            
        except Exception as e:
            axes[0, 2].text(0.5, 0.5, f'Feature importance\nnot available:\n{str(e)[:50]}...', 
                           ha='center', va='center', transform=axes[0, 2].transAxes)
        
        # Panel 4: Residual histogram
        axes[1, 0].hist(residuals, bins=min(25, len(residuals)//5), alpha=0.7, 
                       edgecolor='black', color='lightblue')
        axes[1, 0].set_xlabel('Residuals (PPG)')
        axes[1, 0].set_ylabel('Frequency')
        axes[1, 0].set_title('Residual Distribution')
        axes[1, 0].grid(True, alpha=0.3)
        
        # Panel 5: Enhanced Performance Comparison
        metrics = ['Train R²', 'Test R²', 'CV Mean']
        values = [results['train_r2'], results['test_r2'], results['cv_mean']]
        colors_perf = ['lightcoral', 'lightblue', 'lightgreen']
        
        bars = axes[1, 1].bar(metrics, values, alpha=0.7, color=colors_perf)
        axes[1, 1].set_ylabel('R² Score')
        axes[1, 1].set_title('Model Performance (Points Per Game)')
        axes[1, 1].set_ylim(0, max(values) * 1.1)
        axes[1, 1].grid(True, alpha=0.3)
        
        # Add value labels on bars
        for bar, value in zip(bars, values):
            axes[1, 1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.01,
                           f'{value:.3f}', ha='center', va='bottom', fontsize=10)
        
        # Panel 6: Enhanced Model Configuration Summary for v6.0
        axes[1, 2].axis('off')
        config_text = f"Enhanced Hockey Model v6.0 \n"
        config_text += f"Target: Points Per Game\n"
        config_text += f"Model: {results['model_type']}\n"
        config_text += f"Training samples: {results['n_train']}\n"
        config_text += f"Test samples: {results['n_test']}\n"
        config_text += f"Features selected: {results['n_features_selected']}\n\n"
        
        config_text += "New v6.0 Features:\n"
        config_text += "• Experience modeling\n"
        config_text += "• COVID season controls\n"
        config_text += "• Interaction terms\n"
        config_text += "• Polynomial features\n"
        config_text += "• DATA LEAKAGE FIXED\n\n"
        
        config_text += "Best Parameters:\n"
        if 'best_params' in results and results['best_params']:
            for key, value in list(results['best_params'].items())[:6]:  # Show first 6 params
                config_text += f"  {key}: {value}\n"
        
        axes[1, 2].text(0.1, 0.9, config_text, transform=axes[1, 2].transAxes, 
                       fontsize=9, verticalalignment='top', fontfamily='monospace')
        axes[1, 2].set_title('Enhanced Model Configuration v6.0')
        
        plt.tight_layout()
        
        if save_path:
            os.makedirs(os.path.dirname(save_path), exist_ok=True)
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
            print(f"Enhanced v6.0 plot saved to: {save_path}")
        else:
            plt.show()
        
        plt.close()

def main():
    """
    Main function for Enhanced Hockey Points Per Game Predictor v6.0 - DATA LEAKAGE FIXED.
    
    NEW v6.0 Features:
    - Points per game prediction instead of total points
    - Experience features and career trajectory modeling
    - COVID season controls
    - Polynomial and interaction terms
    - Dual prediction output (actual games vs 82 games)
    - Enhanced regularization for expanded feature set
    - COMPREHENSIVE DATA LEAKAGE PREVENTION
    """
    
    print("Enhanced Hockey Points Per Game Predictor v6.0 - Experience + Non-Linear Features - DATA LEAKAGE FIXED")
    print("=" * 100)
    print(f"Run started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"NEW v6.0 FEATURES: Points per game target, Experience features, COVID controls, Interactions")
    print(f"CRITICAL FIX: Comprehensive exclusion of ALL current season variables to prevent data leakage")
    print(f"PRIMARY DATA SOURCE: data_output/skater_team_data.csv (single team structure)")
    
    # Setup paths and find CSV file
    try:
        csv_path = find_csv_file()
        plots_dir, results_dir = setup_output_directories()
    except FileNotFoundError as e:
        print(f"\nERROR: {e}")
        print("Please ensure your merged player-team CSV file is accessible and try again.")
        return
    except Exception as e:
        print(f"\nERROR setting up paths: {e}")
        return
    
    # Setup output file
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = os.path.join(results_dir, f'enhanced_points_per_game_prediction_v6.0_{timestamp}.txt')
    
    # Setup output manager
    output_manager = OutputManager(output_file)
    sys.stdout = output_manager
    
    try:
        print("Enhanced Hockey Points Per Game Predictor v6.0 - DATA LEAKAGE FIXED")
        print("=" * 100)
        print(f"Run started at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Data file: {csv_path}")
        print(f"Results will be saved to: {output_file}")
        print(f"CRITICAL: This version prevents ALL data leakage by excluding current season variables")
        
        # TRAINING A: All data with enhanced features
        print(f"\n{'='*100}")
        print("TRAINING A: ALL DATA WITH ENHANCED FEATURES (v6.0 - LEAKAGE FIXED)")
        print('='*100)
        
        best_results_all = None
        best_config_all = None
        best_r2_all = -1
        
        # Test configurations
        configs = [
            {'lag_years': 2, 'min_training_year': None, 'use_feature_selection': True},
            {'lag_years': 1, 'min_training_year': None, 'use_feature_selection': True},
            {'lag_years': 3, 'min_training_year': None, 'use_feature_selection': True}
        ]
        
        for config in configs:
            print(f"\nTesting {config['lag_years']}-year lags (ALL DATA)")
            print('-' * 80)
            
            try:
                predictor = EnhancedHockeyPointsPerGamePredictor(**config)
                
                print("Loading and enhancing data...")
                df = predictor.load_data(csv_path)
                
                print("Creating lag features with experience...")
                df_with_lags = predictor.create_lag_features(df)
                
                print("Engineering enhanced features...")
                df_engineered = predictor.engineer_features(df_with_lags)
                
                print("Preparing enhanced feature set with comprehensive exclusions...")
                X, y = predictor.prepare_features(df_engineered)
                
                print(f"Final dataset: {len(X)} observations, {X.shape[1] if len(X) > 0 else 0} features")
                
                if len(X) < 50:
                    print(f"Insufficient data: {len(X)} observations")
                    continue
                
                # Test models
                models = ['random_forest', 'ridge', 'gradient_boosting', 'lasso', 'elastic_net']
                
                for model_type in models:
                    try:
                        print(f"\n  Testing {model_type}...")
                        results = predictor.train_model_with_enhanced_regularization(X, y, model_type=model_type)
                        
                        model_score = results['r2'] - (results['overfitting_ratio'] * 0.1)
                        
                        if model_score > best_r2_all:
                            best_r2_all = model_score
                            best_results_all = results
                            best_config_all = {**config, 'model_type': model_type, 'predictor': predictor}
                            print(f"    New best model: {model_type} with adjusted score = {model_score:.3f}")
                            
                    except Exception as e:
                        print(f"    Error with {model_type}: {e}")
                        continue
                        
            except Exception as e:
                print(f"Error with configuration {config}: {e}")
                continue
        
        # TRAINING B: Predict 2024-2025 with dual output
        print(f"\n{'='*100}")
        print("TRAINING B: PREDICT 2024-2025 WITH DUAL OUTPUT (v6.0 - LEAKAGE FIXED)")
        print('='*100)
        
        best_results_pred = None
        best_config_pred = None
        best_r2_pred = -1
        best_predictions = None
        
        for config in configs:
            print(f"\nTesting {config['lag_years']}-year lags (EXCLUDING 2024-2025)")
            print('-' * 80)
            
            try:
                predictor = EnhancedHockeyPointsPerGamePredictor(**config)
                
                print("Loading and enhancing data...")
                df_full = predictor.load_data(csv_path)
                
                # Split data: exclude 2024-2025 for training
                df_train = df_full[df_full['year'] != 2024].copy()
                
                print(f"Full dataset: {len(df_full)} observations")
                print(f"Training dataset (no 2024-2025): {len(df_train)} observations")
                print(f"2024-2025 data: {len(df_full[df_full['year'] == 2024])} observations")
                
                print("Creating lag features with experience...")
                df_with_lags = predictor.create_lag_features(df_train)
                
                print("Engineering enhanced features...")
                df_engineered = predictor.engineer_features(df_with_lags)
                
                print("Preparing enhanced feature set with comprehensive exclusions...")
                X, y = predictor.prepare_features(df_engineered)
                
                print(f"Final training dataset: {len(X)} observations")
                
                if len(X) < 50:
                    print(f"Insufficient training data: {len(X)} observations")
                    continue
                
                # Test models
                models = ['random_forest', 'ridge', 'gradient_boosting', 'lasso', 'elastic_net']
                
                for model_type in models:
                    try:
                        print(f"\n  Testing {model_type}...")
                        results = predictor.train_model_with_enhanced_regularization(X, y, model_type=model_type)
                        
                        model_score = results['r2'] - (results['overfitting_ratio'] * 0.1)
                        
                        if model_score > best_r2_pred:
                            best_r2_pred = model_score
                            best_results_pred = results
                            best_config_pred = {**config, 'model_type': model_type, 'predictor': predictor}
                            print(f"    New best prediction model: {model_type} with adjusted score = {model_score:.3f}")
                            
                            # Generate dual predictions
                            try:
                                print("    Generating 2024-2025 dual predictions...")
                                df_full_with_lags = predictor.create_lag_features(df_full)
                                df_full_engineered = predictor.engineer_features(df_full_with_lags)
                                predictions = predictor.predict_season_with_dual_output(df_full_engineered, 2024)
                                best_predictions = predictions
                                print(f"    Successfully generated predictions for {len(predictions)} players")
                            except Exception as e:
                                print(f"    Error generating predictions: {e}")
                                best_predictions = None
                            
                    except Exception as e:
                        print(f"    Error with {model_type}: {e}")
                        continue
                        
            except Exception as e:
                print(f"Error with configuration {config}: {e}")
                continue
        
        # Display comprehensive results
        print(f"\n{'='*100}")
        print("ENHANCED RESULTS SUMMARY (v6.0 - DATA LEAKAGE FIXED)")
        print('='*100)
        
        if best_results_all:
            print(f"\nTRAINING A - ALL DATA (ENHANCED FEATURES v6.0 - LEAKAGE FIXED):")
            print(f"  Best configuration: {best_config_all['lag_years']}-year lags, {best_config_all['model_type']}")
            print(f"  R² Score: {best_results_all['r2']:.3f}")
            print(f"  RMSE: {best_results_all['rmse']:.4f} points per game")
            print(f"  MAE: {best_results_all['mae']:.4f} points per game")
            print(f"  Overfitting Ratio: {best_results_all['overfitting_ratio']:.3f}")
            print(f"  Features Selected: {best_results_all['n_features_selected']}")
            
            # Generate and save enhanced diagnostic plot
            plot_filename = os.path.join(plots_dir, f'enhanced_points_per_game_model_v6.0_all_data_{timestamp}.png')
            try:
                best_config_all['predictor'].plot_enhanced_results_v6(best_results_all, save_path=plot_filename)
                print(f"All data plot saved to: {plot_filename}")
            except Exception as e:
                print(f"Could not generate plot: {e}")
            
            # Enhanced feature importance with v6.0 categories
            print(f"\nTop 20 Most Important Features (Enhanced v6.0 Analysis - NO DATA LEAKAGE):")
            print("-" * 90)
            try:
                importance_df = best_config_all['predictor'].get_enhanced_feature_importance(20)
                for idx, row in importance_df.iterrows():
                    print(f"{idx+1:2d}. {row['feature']:40} {row['importance']:.4f} ({row['type']})")
            except Exception as e:
                print(f"Could not display feature importance: {e}")
        
        if best_results_pred and best_predictions is not None:
            print(f"\nTRAINING B - PREDICT 2024-2025 (ENHANCED v6.0 - LEAKAGE FIXED):")
            print(f"  Best configuration: {best_config_pred['lag_years']}-year lags, {best_config_pred['model_type']}")
            print(f"  R² Score: {best_results_pred['r2']:.3f}")
            print(f"  RMSE: {best_results_pred['rmse']:.4f} points per game")
            print(f"  Overfitting Ratio: {best_results_pred['overfitting_ratio']:.3f}")
            
            # Generate and save prediction scenario diagnostic plot
            plot_filename = os.path.join(plots_dir, f'enhanced_points_per_game_model_v6.0_prediction_{timestamp}.png')
            try:
                best_config_pred['predictor'].plot_enhanced_results_v6(best_results_pred, save_path=plot_filename)
                print(f"Prediction plot saved to: {plot_filename}")
            except Exception as e:
                print(f"Could not generate prediction plot: {e}")
            
            # NEW v6.0: Dual ranking output
            print(f"\nTOP 50 PLAYERS - 2024-2025 DUAL PROJECTIONS (DATA LEAKAGE FIXED):")
            print("=" * 120)
            print(f"{'Rank':<4} {'Player Name':<30} {'PPG':<6} {'Games':<6} {'Points (Actual)':<15} {'Points (82 Games)':<16} {'Actual Points':<12}")
            print("-" * 120)
            
            for idx, row in best_predictions.head(50).iterrows():
                actual_total = row['actual_total_points'] if not pd.isna(row['actual_total_points']) else 'N/A'
                print(f"{idx+1:<4} {row['player_name']:<30} {row['predicted_ppg']:<6.2f} {row['actual_games']:<6.0f} "
                      f"{row['predicted_points_actual']:<15.1f} {row['predicted_points_82games']:<16.1f} {actual_total:<12}")
        
        # Enhanced summary for v6.0 - DATA LEAKAGE FIXED
        print(f"\n{'='*100}")
        print("NEW FEATURES IN VERSION 6.0 - DATA LEAKAGE FIXED:")
        print('='*100)
        print("• TARGET CHANGE: Predicts points per game instead of total points")
        print("• EXPERIENCE FEATURES: Years played with polynomial and interaction terms")
        print("• COVID CONTROLS: Special handling for 2019-2020 and 2020-2021 seasons")
        print("• TEAM STRUCTURE: Updated for single team format (wins to face_off_win_pct_team)")
        print("• NON-LINEAR FEATURES: Polynomial terms and interaction effects")
        print("• DUAL OUTPUT: Rankings by total points for (a) actual games and (b) 82 games")
        print("• ENHANCED REGULARIZATION: Stronger controls for expanded feature complexity")
        print("• CAREER MODELING: Rookie, prime, and veteran performance differentials")
        print("• INTERACTION TERMS: Experience × performance cross-effects")
        print("• TEMPORAL CONTROLS: League-wide effects and anomalous season handling")
        print("• CRITICAL FIX: Comprehensive exclusion of ALL current season variables")
        print("• DATA LEAKAGE PREVENTION: Only lagged variables, engineered features, and controls used")
        
        print(f"\nRun completed at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Results saved to: {output_file}")
        print(f"IMPORTANT: This version prevents data leakage - feature importance should show ONLY lagged variables")
    
    finally:
        # Restore stdout and close file
        sys.stdout = output_manager.terminal
        output_manager.close()

if __name__ == "__main__":
    main()